/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActEvtLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActEvtLogRecord extends UpdatableRecordImpl<ActEvtLogRecord> implements Record12<Long, String, String, String, String, String, Timestamp, String, byte[], String, Timestamp, Byte> {

    private static final long serialVersionUID = -1348536048;

    /**
     * Setter for <code>bysj.act_evt_log.LOG_NR_</code>.
     */
    public void setLogNr_(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.LOG_NR_</code>.
     */
    public Long getLogNr_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bysj.act_evt_log.TYPE_</code>.
     */
    public void setType_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.TYPE_</code>.
     */
    public String getType_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.act_evt_log.PROC_DEF_ID_</code>.
     */
    public void setProcDefId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.PROC_DEF_ID_</code>.
     */
    public String getProcDefId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_evt_log.PROC_INST_ID_</code>.
     */
    public void setProcInstId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.PROC_INST_ID_</code>.
     */
    public String getProcInstId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_evt_log.EXECUTION_ID_</code>.
     */
    public void setExecutionId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.EXECUTION_ID_</code>.
     */
    public String getExecutionId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_evt_log.TASK_ID_</code>.
     */
    public void setTaskId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.TASK_ID_</code>.
     */
    public String getTaskId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.act_evt_log.TIME_STAMP_</code>.
     */
    public void setTimeStamp_(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.TIME_STAMP_</code>.
     */
    public Timestamp getTimeStamp_() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>bysj.act_evt_log.USER_ID_</code>.
     */
    public void setUserId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.USER_ID_</code>.
     */
    public String getUserId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.act_evt_log.DATA_</code>.
     */
    public void setData_(byte... value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.DATA_</code>.
     */
    public byte[] getData_() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>bysj.act_evt_log.LOCK_OWNER_</code>.
     */
    public void setLockOwner_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.LOCK_OWNER_</code>.
     */
    public String getLockOwner_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bysj.act_evt_log.LOCK_TIME_</code>.
     */
    public void setLockTime_(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.LOCK_TIME_</code>.
     */
    public Timestamp getLockTime_() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>bysj.act_evt_log.IS_PROCESSED_</code>.
     */
    public void setIsProcessed_(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>bysj.act_evt_log.IS_PROCESSED_</code>.
     */
    public Byte getIsProcessed_() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, Timestamp, String, byte[], String, Timestamp, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, String, Timestamp, String, byte[], String, Timestamp, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ActEvtLog.ACT_EVT_LOG.LOG_NR_;
    }

    @Override
    public Field<String> field2() {
        return ActEvtLog.ACT_EVT_LOG.TYPE_;
    }

    @Override
    public Field<String> field3() {
        return ActEvtLog.ACT_EVT_LOG.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActEvtLog.ACT_EVT_LOG.PROC_INST_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActEvtLog.ACT_EVT_LOG.EXECUTION_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActEvtLog.ACT_EVT_LOG.TASK_ID_;
    }

    @Override
    public Field<Timestamp> field7() {
        return ActEvtLog.ACT_EVT_LOG.TIME_STAMP_;
    }

    @Override
    public Field<String> field8() {
        return ActEvtLog.ACT_EVT_LOG.USER_ID_;
    }

    @Override
    public Field<byte[]> field9() {
        return ActEvtLog.ACT_EVT_LOG.DATA_;
    }

    @Override
    public Field<String> field10() {
        return ActEvtLog.ACT_EVT_LOG.LOCK_OWNER_;
    }

    @Override
    public Field<Timestamp> field11() {
        return ActEvtLog.ACT_EVT_LOG.LOCK_TIME_;
    }

    @Override
    public Field<Byte> field12() {
        return ActEvtLog.ACT_EVT_LOG.IS_PROCESSED_;
    }

    @Override
    public Long component1() {
        return getLogNr_();
    }

    @Override
    public String component2() {
        return getType_();
    }

    @Override
    public String component3() {
        return getProcDefId_();
    }

    @Override
    public String component4() {
        return getProcInstId_();
    }

    @Override
    public String component5() {
        return getExecutionId_();
    }

    @Override
    public String component6() {
        return getTaskId_();
    }

    @Override
    public Timestamp component7() {
        return getTimeStamp_();
    }

    @Override
    public String component8() {
        return getUserId_();
    }

    @Override
    public byte[] component9() {
        return getData_();
    }

    @Override
    public String component10() {
        return getLockOwner_();
    }

    @Override
    public Timestamp component11() {
        return getLockTime_();
    }

    @Override
    public Byte component12() {
        return getIsProcessed_();
    }

    @Override
    public Long value1() {
        return getLogNr_();
    }

    @Override
    public String value2() {
        return getType_();
    }

    @Override
    public String value3() {
        return getProcDefId_();
    }

    @Override
    public String value4() {
        return getProcInstId_();
    }

    @Override
    public String value5() {
        return getExecutionId_();
    }

    @Override
    public String value6() {
        return getTaskId_();
    }

    @Override
    public Timestamp value7() {
        return getTimeStamp_();
    }

    @Override
    public String value8() {
        return getUserId_();
    }

    @Override
    public byte[] value9() {
        return getData_();
    }

    @Override
    public String value10() {
        return getLockOwner_();
    }

    @Override
    public Timestamp value11() {
        return getLockTime_();
    }

    @Override
    public Byte value12() {
        return getIsProcessed_();
    }

    @Override
    public ActEvtLogRecord value1(Long value) {
        setLogNr_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value2(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value3(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value4(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value5(String value) {
        setExecutionId_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value6(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value7(Timestamp value) {
        setTimeStamp_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value8(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value9(byte... value) {
        setData_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value10(String value) {
        setLockOwner_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value11(Timestamp value) {
        setLockTime_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord value12(Byte value) {
        setIsProcessed_(value);
        return this;
    }

    @Override
    public ActEvtLogRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8, byte[] value9, String value10, Timestamp value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActEvtLogRecord
     */
    public ActEvtLogRecord() {
        super(ActEvtLog.ACT_EVT_LOG);
    }

    /**
     * Create a detached, initialised ActEvtLogRecord
     */
    public ActEvtLogRecord(Long logNr_, String type_, String procDefId_, String procInstId_, String executionId_, String taskId_, Timestamp timeStamp_, String userId_, byte[] data_, String lockOwner_, Timestamp lockTime_, Byte isProcessed_) {
        super(ActEvtLog.ACT_EVT_LOG);

        set(0, logNr_);
        set(1, type_);
        set(2, procDefId_);
        set(3, procInstId_);
        set(4, executionId_);
        set(5, taskId_);
        set(6, timeStamp_);
        set(7, userId_);
        set(8, data_);
        set(9, lockOwner_);
        set(10, lockTime_);
        set(11, isProcessed_);
    }
}
