/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActGeBytearray;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActGeBytearrayRecord extends UpdatableRecordImpl<ActGeBytearrayRecord> implements Record6<String, Integer, String, String, byte[], Byte> {

    private static final long serialVersionUID = -1283257613;

    /**
     * Setter for <code>bysj.act_ge_bytearray.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_ge_bytearray.REV_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.REV_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bysj.act_ge_bytearray.NAME_</code>.
     */
    public void setName_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.NAME_</code>.
     */
    public String getName_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_ge_bytearray.DEPLOYMENT_ID_</code>.
     */
    public void setDeploymentId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.DEPLOYMENT_ID_</code>.
     */
    public String getDeploymentId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_ge_bytearray.BYTES_</code>.
     */
    public void setBytes_(byte... value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.BYTES_</code>.
     */
    public byte[] getBytes_() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>bysj.act_ge_bytearray.GENERATED_</code>.
     */
    public void setGenerated_(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_ge_bytearray.GENERATED_</code>.
     */
    public Byte getGenerated_() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, Integer, String, String, byte[], Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, Integer, String, String, byte[], Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.NAME_;
    }

    @Override
    public Field<String> field4() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.DEPLOYMENT_ID_;
    }

    @Override
    public Field<byte[]> field5() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.BYTES_;
    }

    @Override
    public Field<Byte> field6() {
        return ActGeBytearray.ACT_GE_BYTEARRAY.GENERATED_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getName_();
    }

    @Override
    public String component4() {
        return getDeploymentId_();
    }

    @Override
    public byte[] component5() {
        return getBytes_();
    }

    @Override
    public Byte component6() {
        return getGenerated_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getName_();
    }

    @Override
    public String value4() {
        return getDeploymentId_();
    }

    @Override
    public byte[] value5() {
        return getBytes_();
    }

    @Override
    public Byte value6() {
        return getGenerated_();
    }

    @Override
    public ActGeBytearrayRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord value3(String value) {
        setName_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord value4(String value) {
        setDeploymentId_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord value5(byte... value) {
        setBytes_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord value6(Byte value) {
        setGenerated_(value);
        return this;
    }

    @Override
    public ActGeBytearrayRecord values(String value1, Integer value2, String value3, String value4, byte[] value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActGeBytearrayRecord
     */
    public ActGeBytearrayRecord() {
        super(ActGeBytearray.ACT_GE_BYTEARRAY);
    }

    /**
     * Create a detached, initialised ActGeBytearrayRecord
     */
    public ActGeBytearrayRecord(String id_, Integer rev_, String name_, String deploymentId_, byte[] bytes_, Byte generated_) {
        super(ActGeBytearray.ACT_GE_BYTEARRAY);

        set(0, id_);
        set(1, rev_);
        set(2, name_);
        set(3, deploymentId_);
        set(4, bytes_);
        set(5, generated_);
    }
}
