/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActHiAttachment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiAttachmentRecord extends UpdatableRecordImpl<ActHiAttachmentRecord> implements Record11<String, Integer, String, String, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 176462207;

    /**
     * Setter for <code>bysj.act_hi_attachment.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.REV_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.REV_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.USER_ID_</code>.
     */
    public void setUserId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.USER_ID_</code>.
     */
    public String getUserId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.NAME_</code>.
     */
    public void setName_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.NAME_</code>.
     */
    public String getName_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.DESCRIPTION_</code>.
     */
    public void setDescription_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.DESCRIPTION_</code>.
     */
    public String getDescription_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.TYPE_</code>.
     */
    public void setType_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.TYPE_</code>.
     */
    public String getType_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.TASK_ID_</code>.
     */
    public void setTaskId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.TASK_ID_</code>.
     */
    public String getTaskId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.PROC_INST_ID_</code>.
     */
    public void setProcInstId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.PROC_INST_ID_</code>.
     */
    public String getProcInstId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.URL_</code>.
     */
    public void setUrl_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.URL_</code>.
     */
    public String getUrl_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.CONTENT_ID_</code>.
     */
    public void setContentId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.CONTENT_ID_</code>.
     */
    public String getContentId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bysj.act_hi_attachment.TIME_</code>.
     */
    public void setTime_(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.act_hi_attachment.TIME_</code>.
     */
    public Timestamp getTime_() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, Integer, String, String, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, Integer, String, String, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.USER_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.NAME_;
    }

    @Override
    public Field<String> field5() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.DESCRIPTION_;
    }

    @Override
    public Field<String> field6() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.TYPE_;
    }

    @Override
    public Field<String> field7() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.TASK_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.PROC_INST_ID_;
    }

    @Override
    public Field<String> field9() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.URL_;
    }

    @Override
    public Field<String> field10() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.CONTENT_ID_;
    }

    @Override
    public Field<Timestamp> field11() {
        return ActHiAttachment.ACT_HI_ATTACHMENT.TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getUserId_();
    }

    @Override
    public String component4() {
        return getName_();
    }

    @Override
    public String component5() {
        return getDescription_();
    }

    @Override
    public String component6() {
        return getType_();
    }

    @Override
    public String component7() {
        return getTaskId_();
    }

    @Override
    public String component8() {
        return getProcInstId_();
    }

    @Override
    public String component9() {
        return getUrl_();
    }

    @Override
    public String component10() {
        return getContentId_();
    }

    @Override
    public Timestamp component11() {
        return getTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getUserId_();
    }

    @Override
    public String value4() {
        return getName_();
    }

    @Override
    public String value5() {
        return getDescription_();
    }

    @Override
    public String value6() {
        return getType_();
    }

    @Override
    public String value7() {
        return getTaskId_();
    }

    @Override
    public String value8() {
        return getProcInstId_();
    }

    @Override
    public String value9() {
        return getUrl_();
    }

    @Override
    public String value10() {
        return getContentId_();
    }

    @Override
    public Timestamp value11() {
        return getTime_();
    }

    @Override
    public ActHiAttachmentRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value3(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value4(String value) {
        setName_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value5(String value) {
        setDescription_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value6(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value7(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value8(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value9(String value) {
        setUrl_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value10(String value) {
        setContentId_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord value11(Timestamp value) {
        setTime_(value);
        return this;
    }

    @Override
    public ActHiAttachmentRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiAttachmentRecord
     */
    public ActHiAttachmentRecord() {
        super(ActHiAttachment.ACT_HI_ATTACHMENT);
    }

    /**
     * Create a detached, initialised ActHiAttachmentRecord
     */
    public ActHiAttachmentRecord(String id_, Integer rev_, String userId_, String name_, String description_, String type_, String taskId_, String procInstId_, String url_, String contentId_, Timestamp time_) {
        super(ActHiAttachment.ACT_HI_ATTACHMENT);

        set(0, id_);
        set(1, rev_);
        set(2, userId_);
        set(3, name_);
        set(4, description_);
        set(5, type_);
        set(6, taskId_);
        set(7, procInstId_);
        set(8, url_);
        set(9, contentId_);
        set(10, time_);
    }
}
