/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActHiIdentitylink;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiIdentitylinkRecord extends UpdatableRecordImpl<ActHiIdentitylinkRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -176364135;

    /**
     * Setter for <code>bysj.act_hi_identitylink.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_hi_identitylink.GROUP_ID_</code>.
     */
    public void setGroupId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.GROUP_ID_</code>.
     */
    public String getGroupId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.act_hi_identitylink.TYPE_</code>.
     */
    public void setType_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.TYPE_</code>.
     */
    public String getType_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_hi_identitylink.USER_ID_</code>.
     */
    public void setUserId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.USER_ID_</code>.
     */
    public String getUserId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_hi_identitylink.TASK_ID_</code>.
     */
    public void setTaskId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.TASK_ID_</code>.
     */
    public String getTaskId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_hi_identitylink.PROC_INST_ID_</code>.
     */
    public void setProcInstId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_hi_identitylink.PROC_INST_ID_</code>.
     */
    public String getProcInstId_() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.GROUP_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TYPE_;
    }

    @Override
    public Field<String> field4() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.USER_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TASK_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.PROC_INST_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getGroupId_();
    }

    @Override
    public String component3() {
        return getType_();
    }

    @Override
    public String component4() {
        return getUserId_();
    }

    @Override
    public String component5() {
        return getTaskId_();
    }

    @Override
    public String component6() {
        return getProcInstId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getGroupId_();
    }

    @Override
    public String value3() {
        return getType_();
    }

    @Override
    public String value4() {
        return getUserId_();
    }

    @Override
    public String value5() {
        return getTaskId_();
    }

    @Override
    public String value6() {
        return getProcInstId_();
    }

    @Override
    public ActHiIdentitylinkRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value2(String value) {
        setGroupId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value3(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value4(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value5(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value6(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiIdentitylinkRecord
     */
    public ActHiIdentitylinkRecord() {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK);
    }

    /**
     * Create a detached, initialised ActHiIdentitylinkRecord
     */
    public ActHiIdentitylinkRecord(String id_, String groupId_, String type_, String userId_, String taskId_, String procInstId_) {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK);

        set(0, id_);
        set(1, groupId_);
        set(2, type_);
        set(3, userId_);
        set(4, taskId_);
        set(5, procInstId_);
    }
}
