/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActHiActinst;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiActinstRecord extends UpdatableRecordImpl<ActHiActinstRecord> implements Record15<String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Long, String, String> {

    private static final long serialVersionUID = -1525828091;

    /**
     * Setter for <code>bysj.act_hi_actinst.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.PROC_DEF_ID_</code>.
     */
    public void setProcDefId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.PROC_DEF_ID_</code>.
     */
    public String getProcDefId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.PROC_INST_ID_</code>.
     */
    public void setProcInstId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.PROC_INST_ID_</code>.
     */
    public String getProcInstId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.EXECUTION_ID_</code>.
     */
    public void setExecutionId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.EXECUTION_ID_</code>.
     */
    public String getExecutionId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.ACT_ID_</code>.
     */
    public void setActId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.ACT_ID_</code>.
     */
    public String getActId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.TASK_ID_</code>.
     */
    public void setTaskId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.TASK_ID_</code>.
     */
    public String getTaskId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.CALL_PROC_INST_ID_</code>.
     */
    public void setCallProcInstId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.CALL_PROC_INST_ID_</code>.
     */
    public String getCallProcInstId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.ACT_NAME_</code>.
     */
    public void setActName_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.ACT_NAME_</code>.
     */
    public String getActName_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.ACT_TYPE_</code>.
     */
    public void setActType_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.ACT_TYPE_</code>.
     */
    public String getActType_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.ASSIGNEE_</code>.
     */
    public void setAssignee_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.ASSIGNEE_</code>.
     */
    public String getAssignee_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.START_TIME_</code>.
     */
    public void setStartTime_(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.START_TIME_</code>.
     */
    public Timestamp getStartTime_() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.END_TIME_</code>.
     */
    public void setEndTime_(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.END_TIME_</code>.
     */
    public Timestamp getEndTime_() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.DURATION_</code>.
     */
    public void setDuration_(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.DURATION_</code>.
     */
    public Long getDuration_() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.DELETE_REASON_</code>.
     */
    public void setDeleteReason_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.DELETE_REASON_</code>.
     */
    public String getDeleteReason_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>bysj.act_hi_actinst.TENANT_ID_</code>.
     */
    public void setTenantId_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>bysj.act_hi_actinst.TENANT_ID_</code>.
     */
    public String getTenantId_() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Long, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Long, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiActinst.ACT_HI_ACTINST.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiActinst.ACT_HI_ACTINST.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiActinst.ACT_HI_ACTINST.PROC_INST_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActHiActinst.ACT_HI_ACTINST.EXECUTION_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiActinst.ACT_HI_ACTINST.ACT_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiActinst.ACT_HI_ACTINST.TASK_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActHiActinst.ACT_HI_ACTINST.CALL_PROC_INST_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActHiActinst.ACT_HI_ACTINST.ACT_NAME_;
    }

    @Override
    public Field<String> field9() {
        return ActHiActinst.ACT_HI_ACTINST.ACT_TYPE_;
    }

    @Override
    public Field<String> field10() {
        return ActHiActinst.ACT_HI_ACTINST.ASSIGNEE_;
    }

    @Override
    public Field<Timestamp> field11() {
        return ActHiActinst.ACT_HI_ACTINST.START_TIME_;
    }

    @Override
    public Field<Timestamp> field12() {
        return ActHiActinst.ACT_HI_ACTINST.END_TIME_;
    }

    @Override
    public Field<Long> field13() {
        return ActHiActinst.ACT_HI_ACTINST.DURATION_;
    }

    @Override
    public Field<String> field14() {
        return ActHiActinst.ACT_HI_ACTINST.DELETE_REASON_;
    }

    @Override
    public Field<String> field15() {
        return ActHiActinst.ACT_HI_ACTINST.TENANT_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getProcDefId_();
    }

    @Override
    public String component3() {
        return getProcInstId_();
    }

    @Override
    public String component4() {
        return getExecutionId_();
    }

    @Override
    public String component5() {
        return getActId_();
    }

    @Override
    public String component6() {
        return getTaskId_();
    }

    @Override
    public String component7() {
        return getCallProcInstId_();
    }

    @Override
    public String component8() {
        return getActName_();
    }

    @Override
    public String component9() {
        return getActType_();
    }

    @Override
    public String component10() {
        return getAssignee_();
    }

    @Override
    public Timestamp component11() {
        return getStartTime_();
    }

    @Override
    public Timestamp component12() {
        return getEndTime_();
    }

    @Override
    public Long component13() {
        return getDuration_();
    }

    @Override
    public String component14() {
        return getDeleteReason_();
    }

    @Override
    public String component15() {
        return getTenantId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getProcDefId_();
    }

    @Override
    public String value3() {
        return getProcInstId_();
    }

    @Override
    public String value4() {
        return getExecutionId_();
    }

    @Override
    public String value5() {
        return getActId_();
    }

    @Override
    public String value6() {
        return getTaskId_();
    }

    @Override
    public String value7() {
        return getCallProcInstId_();
    }

    @Override
    public String value8() {
        return getActName_();
    }

    @Override
    public String value9() {
        return getActType_();
    }

    @Override
    public String value10() {
        return getAssignee_();
    }

    @Override
    public Timestamp value11() {
        return getStartTime_();
    }

    @Override
    public Timestamp value12() {
        return getEndTime_();
    }

    @Override
    public Long value13() {
        return getDuration_();
    }

    @Override
    public String value14() {
        return getDeleteReason_();
    }

    @Override
    public String value15() {
        return getTenantId_();
    }

    @Override
    public ActHiActinstRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value2(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value3(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value4(String value) {
        setExecutionId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value5(String value) {
        setActId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value6(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value7(String value) {
        setCallProcInstId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value8(String value) {
        setActName_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value9(String value) {
        setActType_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value10(String value) {
        setAssignee_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value11(Timestamp value) {
        setStartTime_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value12(Timestamp value) {
        setEndTime_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value13(Long value) {
        setDuration_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value14(String value) {
        setDeleteReason_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord value15(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiActinstRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Timestamp value11, Timestamp value12, Long value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiActinstRecord
     */
    public ActHiActinstRecord() {
        super(ActHiActinst.ACT_HI_ACTINST);
    }

    /**
     * Create a detached, initialised ActHiActinstRecord
     */
    public ActHiActinstRecord(String id_, String procDefId_, String procInstId_, String executionId_, String actId_, String taskId_, String callProcInstId_, String actName_, String actType_, String assignee_, Timestamp startTime_, Timestamp endTime_, Long duration_, String deleteReason_, String tenantId_) {
        super(ActHiActinst.ACT_HI_ACTINST);

        set(0, id_);
        set(1, procDefId_);
        set(2, procInstId_);
        set(3, executionId_);
        set(4, actId_);
        set(5, taskId_);
        set(6, callProcInstId_);
        set(7, actName_);
        set(8, actType_);
        set(9, assignee_);
        set(10, startTime_);
        set(11, endTime_);
        set(12, duration_);
        set(13, deleteReason_);
        set(14, tenantId_);
    }
}
