/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActHiDetail;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiDetailRecord extends UpdatableRecordImpl<ActHiDetailRecord> implements Record15<String, String, String, String, String, String, String, String, Integer, Timestamp, String, Double, Long, String, String> {

    private static final long serialVersionUID = 1831470920;

    /**
     * Setter for <code>bysj.act_hi_detail.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.TYPE_</code>.
     */
    public void setType_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.TYPE_</code>.
     */
    public String getType_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.PROC_INST_ID_</code>.
     */
    public void setProcInstId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.PROC_INST_ID_</code>.
     */
    public String getProcInstId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.EXECUTION_ID_</code>.
     */
    public void setExecutionId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.EXECUTION_ID_</code>.
     */
    public String getExecutionId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.TASK_ID_</code>.
     */
    public void setTaskId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.TASK_ID_</code>.
     */
    public String getTaskId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.ACT_INST_ID_</code>.
     */
    public void setActInstId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.ACT_INST_ID_</code>.
     */
    public String getActInstId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.NAME_</code>.
     */
    public void setName_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.NAME_</code>.
     */
    public String getName_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.VAR_TYPE_</code>.
     */
    public void setVarType_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.VAR_TYPE_</code>.
     */
    public String getVarType_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.REV_</code>.
     */
    public void setRev_(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.REV_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.TIME_</code>.
     */
    public void setTime_(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.TIME_</code>.
     */
    public Timestamp getTime_() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.BYTEARRAY_ID_</code>.
     */
    public void setBytearrayId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.BYTEARRAY_ID_</code>.
     */
    public String getBytearrayId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.DOUBLE_</code>.
     */
    public void setDouble_(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.DOUBLE_</code>.
     */
    public Double getDouble_() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.LONG_</code>.
     */
    public void setLong_(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.LONG_</code>.
     */
    public Long getLong_() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.TEXT_</code>.
     */
    public void setText_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.TEXT_</code>.
     */
    public String getText_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>bysj.act_hi_detail.TEXT2_</code>.
     */
    public void setText2_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>bysj.act_hi_detail.TEXT2_</code>.
     */
    public String getText2_() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, String, String, String, String, Integer, Timestamp, String, Double, Long, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, String, String, String, String, String, Integer, Timestamp, String, Double, Long, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiDetail.ACT_HI_DETAIL.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiDetail.ACT_HI_DETAIL.TYPE_;
    }

    @Override
    public Field<String> field3() {
        return ActHiDetail.ACT_HI_DETAIL.PROC_INST_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActHiDetail.ACT_HI_DETAIL.EXECUTION_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiDetail.ACT_HI_DETAIL.TASK_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiDetail.ACT_HI_DETAIL.ACT_INST_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActHiDetail.ACT_HI_DETAIL.NAME_;
    }

    @Override
    public Field<String> field8() {
        return ActHiDetail.ACT_HI_DETAIL.VAR_TYPE_;
    }

    @Override
    public Field<Integer> field9() {
        return ActHiDetail.ACT_HI_DETAIL.REV_;
    }

    @Override
    public Field<Timestamp> field10() {
        return ActHiDetail.ACT_HI_DETAIL.TIME_;
    }

    @Override
    public Field<String> field11() {
        return ActHiDetail.ACT_HI_DETAIL.BYTEARRAY_ID_;
    }

    @Override
    public Field<Double> field12() {
        return ActHiDetail.ACT_HI_DETAIL.DOUBLE_;
    }

    @Override
    public Field<Long> field13() {
        return ActHiDetail.ACT_HI_DETAIL.LONG_;
    }

    @Override
    public Field<String> field14() {
        return ActHiDetail.ACT_HI_DETAIL.TEXT_;
    }

    @Override
    public Field<String> field15() {
        return ActHiDetail.ACT_HI_DETAIL.TEXT2_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getType_();
    }

    @Override
    public String component3() {
        return getProcInstId_();
    }

    @Override
    public String component4() {
        return getExecutionId_();
    }

    @Override
    public String component5() {
        return getTaskId_();
    }

    @Override
    public String component6() {
        return getActInstId_();
    }

    @Override
    public String component7() {
        return getName_();
    }

    @Override
    public String component8() {
        return getVarType_();
    }

    @Override
    public Integer component9() {
        return getRev_();
    }

    @Override
    public Timestamp component10() {
        return getTime_();
    }

    @Override
    public String component11() {
        return getBytearrayId_();
    }

    @Override
    public Double component12() {
        return getDouble_();
    }

    @Override
    public Long component13() {
        return getLong_();
    }

    @Override
    public String component14() {
        return getText_();
    }

    @Override
    public String component15() {
        return getText2_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getType_();
    }

    @Override
    public String value3() {
        return getProcInstId_();
    }

    @Override
    public String value4() {
        return getExecutionId_();
    }

    @Override
    public String value5() {
        return getTaskId_();
    }

    @Override
    public String value6() {
        return getActInstId_();
    }

    @Override
    public String value7() {
        return getName_();
    }

    @Override
    public String value8() {
        return getVarType_();
    }

    @Override
    public Integer value9() {
        return getRev_();
    }

    @Override
    public Timestamp value10() {
        return getTime_();
    }

    @Override
    public String value11() {
        return getBytearrayId_();
    }

    @Override
    public Double value12() {
        return getDouble_();
    }

    @Override
    public Long value13() {
        return getLong_();
    }

    @Override
    public String value14() {
        return getText_();
    }

    @Override
    public String value15() {
        return getText2_();
    }

    @Override
    public ActHiDetailRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value2(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value3(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value4(String value) {
        setExecutionId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value5(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value6(String value) {
        setActInstId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value7(String value) {
        setName_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value8(String value) {
        setVarType_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value9(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value10(Timestamp value) {
        setTime_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value11(String value) {
        setBytearrayId_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value12(Double value) {
        setDouble_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value13(Long value) {
        setLong_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value14(String value) {
        setText_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord value15(String value) {
        setText2_(value);
        return this;
    }

    @Override
    public ActHiDetailRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Timestamp value10, String value11, Double value12, Long value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiDetailRecord
     */
    public ActHiDetailRecord() {
        super(ActHiDetail.ACT_HI_DETAIL);
    }

    /**
     * Create a detached, initialised ActHiDetailRecord
     */
    public ActHiDetailRecord(String id_, String type_, String procInstId_, String executionId_, String taskId_, String actInstId_, String name_, String varType_, Integer rev_, Timestamp time_, String bytearrayId_, Double double_, Long long_, String text_, String text2_) {
        super(ActHiDetail.ACT_HI_DETAIL);

        set(0, id_);
        set(1, type_);
        set(2, procInstId_);
        set(3, executionId_);
        set(4, taskId_);
        set(5, actInstId_);
        set(6, name_);
        set(7, varType_);
        set(8, rev_);
        set(9, time_);
        set(10, bytearrayId_);
        set(11, double_);
        set(12, long_);
        set(13, text_);
        set(14, text2_);
    }
}
