/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActIdUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdUserRecord extends UpdatableRecordImpl<ActIdUserRecord> implements Record7<String, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -147365960;

    /**
     * Setter for <code>bysj.act_id_user.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_id_user.REV_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.REV_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bysj.act_id_user.FIRST_</code>.
     */
    public void setFirst_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.FIRST_</code>.
     */
    public String getFirst_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_id_user.LAST_</code>.
     */
    public void setLast_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.LAST_</code>.
     */
    public String getLast_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_id_user.EMAIL_</code>.
     */
    public void setEmail_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.EMAIL_</code>.
     */
    public String getEmail_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_id_user.PWD_</code>.
     */
    public void setPwd_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.PWD_</code>.
     */
    public String getPwd_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.act_id_user.PICTURE_ID_</code>.
     */
    public void setPictureId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_id_user.PICTURE_ID_</code>.
     */
    public String getPictureId_() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActIdUser.ACT_ID_USER.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActIdUser.ACT_ID_USER.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActIdUser.ACT_ID_USER.FIRST_;
    }

    @Override
    public Field<String> field4() {
        return ActIdUser.ACT_ID_USER.LAST_;
    }

    @Override
    public Field<String> field5() {
        return ActIdUser.ACT_ID_USER.EMAIL_;
    }

    @Override
    public Field<String> field6() {
        return ActIdUser.ACT_ID_USER.PWD_;
    }

    @Override
    public Field<String> field7() {
        return ActIdUser.ACT_ID_USER.PICTURE_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getFirst_();
    }

    @Override
    public String component4() {
        return getLast_();
    }

    @Override
    public String component5() {
        return getEmail_();
    }

    @Override
    public String component6() {
        return getPwd_();
    }

    @Override
    public String component7() {
        return getPictureId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getFirst_();
    }

    @Override
    public String value4() {
        return getLast_();
    }

    @Override
    public String value5() {
        return getEmail_();
    }

    @Override
    public String value6() {
        return getPwd_();
    }

    @Override
    public String value7() {
        return getPictureId_();
    }

    @Override
    public ActIdUserRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value3(String value) {
        setFirst_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value4(String value) {
        setLast_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value5(String value) {
        setEmail_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value6(String value) {
        setPwd_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value7(String value) {
        setPictureId_(value);
        return this;
    }

    @Override
    public ActIdUserRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActIdUserRecord
     */
    public ActIdUserRecord() {
        super(ActIdUser.ACT_ID_USER);
    }

    /**
     * Create a detached, initialised ActIdUserRecord
     */
    public ActIdUserRecord(String id_, Integer rev_, String first_, String last_, String email_, String pwd_, String pictureId_) {
        super(ActIdUser.ACT_ID_USER);

        set(0, id_);
        set(1, rev_);
        set(2, first_);
        set(3, last_);
        set(4, email_);
        set(5, pwd_);
        set(6, pictureId_);
    }
}
