/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.ActReDeployment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReDeploymentRecord extends UpdatableRecordImpl<ActReDeploymentRecord> implements Record7<String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = -936889384;

    /**
     * Setter for <code>bysj.act_re_deployment.ID_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.ID_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.NAME_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.NAME_</code>.
     */
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.CATEGORY_</code>.
     */
    public void setCategory_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.CATEGORY_</code>.
     */
    public String getCategory_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.KEY_</code>.
     */
    public void setKey_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.KEY_</code>.
     */
    public String getKey_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.TENANT_ID_</code>.
     */
    public void setTenantId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.TENANT_ID_</code>.
     */
    public String getTenantId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.DEPLOY_TIME_</code>.
     */
    public void setDeployTime_(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.DEPLOY_TIME_</code>.
     */
    public Timestamp getDeployTime_() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>bysj.act_re_deployment.ENGINE_VERSION_</code>.
     */
    public void setEngineVersion_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.act_re_deployment.ENGINE_VERSION_</code>.
     */
    public String getEngineVersion_() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.NAME_;
    }

    @Override
    public Field<String> field3() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.CATEGORY_;
    }

    @Override
    public Field<String> field4() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.KEY_;
    }

    @Override
    public Field<String> field5() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.TENANT_ID_;
    }

    @Override
    public Field<Timestamp> field6() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.DEPLOY_TIME_;
    }

    @Override
    public Field<String> field7() {
        return ActReDeployment.ACT_RE_DEPLOYMENT.ENGINE_VERSION_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getName_();
    }

    @Override
    public String component3() {
        return getCategory_();
    }

    @Override
    public String component4() {
        return getKey_();
    }

    @Override
    public String component5() {
        return getTenantId_();
    }

    @Override
    public Timestamp component6() {
        return getDeployTime_();
    }

    @Override
    public String component7() {
        return getEngineVersion_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getName_();
    }

    @Override
    public String value3() {
        return getCategory_();
    }

    @Override
    public String value4() {
        return getKey_();
    }

    @Override
    public String value5() {
        return getTenantId_();
    }

    @Override
    public Timestamp value6() {
        return getDeployTime_();
    }

    @Override
    public String value7() {
        return getEngineVersion_();
    }

    @Override
    public ActReDeploymentRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value2(String value) {
        setName_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value3(String value) {
        setCategory_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value4(String value) {
        setKey_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value5(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value6(Timestamp value) {
        setDeployTime_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord value7(String value) {
        setEngineVersion_(value);
        return this;
    }

    @Override
    public ActReDeploymentRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActReDeploymentRecord
     */
    public ActReDeploymentRecord() {
        super(ActReDeployment.ACT_RE_DEPLOYMENT);
    }

    /**
     * Create a detached, initialised ActReDeploymentRecord
     */
    public ActReDeploymentRecord(String id_, String name_, String category_, String key_, String tenantId_, Timestamp deployTime_, String engineVersion_) {
        super(ActReDeployment.ACT_RE_DEPLOYMENT);

        set(0, id_);
        set(1, name_);
        set(2, category_);
        set(3, key_);
        set(4, tenantId_);
        set(5, deployTime_);
        set(6, engineVersion_);
    }
}
