/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.Changemajors;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangemajorsRecord extends UpdatableRecordImpl<ChangemajorsRecord> implements Record17<String, String, Integer, String, String, String, String, String, String, String, Double, String, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -469091332;

    /**
     * Setter for <code>bysj.changemajors.cid</code>. 转专业表主键ID
     */
    public void setCid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.changemajors.cid</code>. 转专业表主键ID
     */
    public String getCid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bysj.changemajors.processInstanceId</code>. 转专业学生ID
     */
    public void setProcessinstanceid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.changemajors.processInstanceId</code>. 转专业学生ID
     */
    public String getProcessinstanceid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.changemajors.userId</code>. 用户ID
     */
    public void setUserid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.changemajors.userId</code>. 用户ID
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bysj.changemajors.reason</code>. 转专业申请理由
     */
    public void setReason(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.changemajors.reason</code>. 转专业申请理由
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.changemajors.currentCollege</code>. 限专业所在学院
     */
    public void setCurrentcollege(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.changemajors.currentCollege</code>. 限专业所在学院
     */
    public String getCurrentcollege() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.changemajors.currentProfession</code>. 现专业
     */
    public void setCurrentprofession(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.changemajors.currentProfession</code>. 现专业
     */
    public String getCurrentprofession() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.changemajors.currentClass</code>. 现班级
     */
    public void setCurrentclass(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.changemajors.currentClass</code>. 现班级
     */
    public String getCurrentclass() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.changemajors.newCollege</code>. 转向专业所在学院
     */
    public void setNewcollege(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.changemajors.newCollege</code>. 转向专业所在学院
     */
    public String getNewcollege() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.changemajors.newProfession</code>. 新专业
     */
    public void setNewprofession(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.changemajors.newProfession</code>. 新专业
     */
    public String getNewprofession() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bysj.changemajors.post</code>. 班内职位
     */
    public void setPost(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.changemajors.post</code>. 班内职位
     */
    public String getPost() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bysj.changemajors.gpa</code>. 学生个人GPA
     */
    public void setGpa(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.changemajors.gpa</code>. 学生个人GPA
     */
    public Double getGpa() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>bysj.changemajors.rank</code>. 成绩排名
     */
    public void setRank(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bysj.changemajors.rank</code>. 成绩排名
     */
    public String getRank() {
        return (String) get(11);
    }

    /**
     * Setter for <code>bysj.changemajors.contest</code>. 申请理由
     */
    public void setContest(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bysj.changemajors.contest</code>. 申请理由
     */
    public String getContest() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bysj.changemajors.society</code>. 参加的社团及职位
     */
    public void setSociety(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>bysj.changemajors.society</code>. 参加的社团及职位
     */
    public String getSociety() {
        return (String) get(13);
    }

    /**
     * Setter for <code>bysj.changemajors.processStatus</code>. 流程状态：0 申请，1 当前教务办，2 当前院长，3 转向教务办，4 转向院长，5 学校教务办，6 全部通过
,7 拒绝，10 完成（班级分配完成，全部任务结束）
     */
    public void setProcessstatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>bysj.changemajors.processStatus</code>. 流程状态：0 申请，1 当前教务办，2 当前院长，3 转向教务办，4 转向院长，5 学校教务办，6 全部通过
,7 拒绝，10 完成（班级分配完成，全部任务结束）
     */
    public Integer getProcessstatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>bysj.changemajors.createTime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>bysj.changemajors.createTime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>bysj.changemajors.updateTime</code>. 更新时间
     */
    public void setUpdatetime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>bysj.changemajors.updateTime</code>. 更新时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<String, String, Integer, String, String, String, String, String, String, String, Double, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<String, String, Integer, String, String, String, String, String, String, String, Double, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Changemajors.CHANGEMAJORS.CID;
    }

    @Override
    public Field<String> field2() {
        return Changemajors.CHANGEMAJORS.PROCESSINSTANCEID;
    }

    @Override
    public Field<Integer> field3() {
        return Changemajors.CHANGEMAJORS.USERID;
    }

    @Override
    public Field<String> field4() {
        return Changemajors.CHANGEMAJORS.REASON;
    }

    @Override
    public Field<String> field5() {
        return Changemajors.CHANGEMAJORS.CURRENTCOLLEGE;
    }

    @Override
    public Field<String> field6() {
        return Changemajors.CHANGEMAJORS.CURRENTPROFESSION;
    }

    @Override
    public Field<String> field7() {
        return Changemajors.CHANGEMAJORS.CURRENTCLASS;
    }

    @Override
    public Field<String> field8() {
        return Changemajors.CHANGEMAJORS.NEWCOLLEGE;
    }

    @Override
    public Field<String> field9() {
        return Changemajors.CHANGEMAJORS.NEWPROFESSION;
    }

    @Override
    public Field<String> field10() {
        return Changemajors.CHANGEMAJORS.POST;
    }

    @Override
    public Field<Double> field11() {
        return Changemajors.CHANGEMAJORS.GPA;
    }

    @Override
    public Field<String> field12() {
        return Changemajors.CHANGEMAJORS.RANK;
    }

    @Override
    public Field<String> field13() {
        return Changemajors.CHANGEMAJORS.CONTEST;
    }

    @Override
    public Field<String> field14() {
        return Changemajors.CHANGEMAJORS.SOCIETY;
    }

    @Override
    public Field<Integer> field15() {
        return Changemajors.CHANGEMAJORS.PROCESSSTATUS;
    }

    @Override
    public Field<Timestamp> field16() {
        return Changemajors.CHANGEMAJORS.CREATETIME;
    }

    @Override
    public Field<Timestamp> field17() {
        return Changemajors.CHANGEMAJORS.UPDATETIME;
    }

    @Override
    public String component1() {
        return getCid();
    }

    @Override
    public String component2() {
        return getProcessinstanceid();
    }

    @Override
    public Integer component3() {
        return getUserid();
    }

    @Override
    public String component4() {
        return getReason();
    }

    @Override
    public String component5() {
        return getCurrentcollege();
    }

    @Override
    public String component6() {
        return getCurrentprofession();
    }

    @Override
    public String component7() {
        return getCurrentclass();
    }

    @Override
    public String component8() {
        return getNewcollege();
    }

    @Override
    public String component9() {
        return getNewprofession();
    }

    @Override
    public String component10() {
        return getPost();
    }

    @Override
    public Double component11() {
        return getGpa();
    }

    @Override
    public String component12() {
        return getRank();
    }

    @Override
    public String component13() {
        return getContest();
    }

    @Override
    public String component14() {
        return getSociety();
    }

    @Override
    public Integer component15() {
        return getProcessstatus();
    }

    @Override
    public Timestamp component16() {
        return getCreatetime();
    }

    @Override
    public Timestamp component17() {
        return getUpdatetime();
    }

    @Override
    public String value1() {
        return getCid();
    }

    @Override
    public String value2() {
        return getProcessinstanceid();
    }

    @Override
    public Integer value3() {
        return getUserid();
    }

    @Override
    public String value4() {
        return getReason();
    }

    @Override
    public String value5() {
        return getCurrentcollege();
    }

    @Override
    public String value6() {
        return getCurrentprofession();
    }

    @Override
    public String value7() {
        return getCurrentclass();
    }

    @Override
    public String value8() {
        return getNewcollege();
    }

    @Override
    public String value9() {
        return getNewprofession();
    }

    @Override
    public String value10() {
        return getPost();
    }

    @Override
    public Double value11() {
        return getGpa();
    }

    @Override
    public String value12() {
        return getRank();
    }

    @Override
    public String value13() {
        return getContest();
    }

    @Override
    public String value14() {
        return getSociety();
    }

    @Override
    public Integer value15() {
        return getProcessstatus();
    }

    @Override
    public Timestamp value16() {
        return getCreatetime();
    }

    @Override
    public Timestamp value17() {
        return getUpdatetime();
    }

    @Override
    public ChangemajorsRecord value1(String value) {
        setCid(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value2(String value) {
        setProcessinstanceid(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value4(String value) {
        setReason(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value5(String value) {
        setCurrentcollege(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value6(String value) {
        setCurrentprofession(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value7(String value) {
        setCurrentclass(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value8(String value) {
        setNewcollege(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value9(String value) {
        setNewprofession(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value10(String value) {
        setPost(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value11(Double value) {
        setGpa(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value12(String value) {
        setRank(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value13(String value) {
        setContest(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value14(String value) {
        setSociety(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value15(Integer value) {
        setProcessstatus(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value16(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    @Override
    public ChangemajorsRecord value17(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    @Override
    public ChangemajorsRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Double value11, String value12, String value13, String value14, Integer value15, Timestamp value16, Timestamp value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChangemajorsRecord
     */
    public ChangemajorsRecord() {
        super(Changemajors.CHANGEMAJORS);
    }

    /**
     * Create a detached, initialised ChangemajorsRecord
     */
    public ChangemajorsRecord(String cid, String processinstanceid, Integer userid, String reason, String currentcollege, String currentprofession, String currentclass, String newcollege, String newprofession, String post, Double gpa, String rank, String contest, String society, Integer processstatus, Timestamp createtime, Timestamp updatetime) {
        super(Changemajors.CHANGEMAJORS);

        set(0, cid);
        set(1, processinstanceid);
        set(2, userid);
        set(3, reason);
        set(4, currentcollege);
        set(5, currentprofession);
        set(6, currentclass);
        set(7, newcollege);
        set(8, newprofession);
        set(9, post);
        set(10, gpa);
        set(11, rank);
        set(12, contest);
        set(13, society);
        set(14, processstatus);
        set(15, createtime);
        set(16, updatetime);
    }
}
