/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.Leave;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaveRecord extends UpdatableRecordImpl<LeaveRecord> implements Record11<Integer, Integer, Timestamp, Timestamp, Timestamp, String, String, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -921687930;

    /**
     * Setter for <code>bysj.leave.lid</code>. 请假表主键ID
     */
    public void setLid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.leave.lid</code>. 请假表主键ID
     */
    public Integer getLid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bysj.leave.nid</code>. 请假人信息ID（参照学生表或教师表）
     */
    public void setNid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.leave.nid</code>. 请假人信息ID（参照学生表或教师表）
     */
    public Integer getNid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bysj.leave.nTime</code>. 请假当前时间
     */
    public void setNtime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.leave.nTime</code>. 请假当前时间
     */
    public Timestamp getNtime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>bysj.leave.sTime</code>. 请假起始时间
     */
    public void setStime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.leave.sTime</code>. 请假起始时间
     */
    public Timestamp getStime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>bysj.leave.eTime</code>. 请假结束时间
     */
    public void setEtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.leave.eTime</code>. 请假结束时间
     */
    public Timestamp getEtime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>bysj.leave.reason</code>. 请假理由
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.leave.reason</code>. 请假理由
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bysj.leave.type</code>. 请假类型：（如：事假，病假等）
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.leave.type</code>. 请假类型：（如：事假，病假等）
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.leave.result</code>. 请假审批结果（0：审批中 1：通过 2：拒绝） 
     */
    public void setResult(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.leave.result</code>. 请假审批结果（0：审批中 1：通过 2：拒绝） 
     */
    public Integer getResult() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>bysj.leave.remark</code>. 审批结果备注
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.leave.remark</code>. 审批结果备注
     */
    public String getRemark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bysj.leave.role</code>. 请假人职位（0：教师 1：学生）
     */
    public void setRole(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.leave.role</code>. 请假人职位（0：教师 1：学生）
     */
    public Integer getRole() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>bysj.leave.tid</code>. 审批人ID
     */
    public void setTid(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.leave.tid</code>. 审批人ID
     */
    public Integer getTid() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Timestamp, Timestamp, Timestamp, String, String, Integer, String, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, Timestamp, Timestamp, Timestamp, String, String, Integer, String, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Leave.LEAVE.LID;
    }

    @Override
    public Field<Integer> field2() {
        return Leave.LEAVE.NID;
    }

    @Override
    public Field<Timestamp> field3() {
        return Leave.LEAVE.NTIME;
    }

    @Override
    public Field<Timestamp> field4() {
        return Leave.LEAVE.STIME;
    }

    @Override
    public Field<Timestamp> field5() {
        return Leave.LEAVE.ETIME;
    }

    @Override
    public Field<String> field6() {
        return Leave.LEAVE.REASON;
    }

    @Override
    public Field<String> field7() {
        return Leave.LEAVE.TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return Leave.LEAVE.RESULT;
    }

    @Override
    public Field<String> field9() {
        return Leave.LEAVE.REMARK;
    }

    @Override
    public Field<Integer> field10() {
        return Leave.LEAVE.ROLE;
    }

    @Override
    public Field<Integer> field11() {
        return Leave.LEAVE.TID;
    }

    @Override
    public Integer component1() {
        return getLid();
    }

    @Override
    public Integer component2() {
        return getNid();
    }

    @Override
    public Timestamp component3() {
        return getNtime();
    }

    @Override
    public Timestamp component4() {
        return getStime();
    }

    @Override
    public Timestamp component5() {
        return getEtime();
    }

    @Override
    public String component6() {
        return getReason();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public Integer component8() {
        return getResult();
    }

    @Override
    public String component9() {
        return getRemark();
    }

    @Override
    public Integer component10() {
        return getRole();
    }

    @Override
    public Integer component11() {
        return getTid();
    }

    @Override
    public Integer value1() {
        return getLid();
    }

    @Override
    public Integer value2() {
        return getNid();
    }

    @Override
    public Timestamp value3() {
        return getNtime();
    }

    @Override
    public Timestamp value4() {
        return getStime();
    }

    @Override
    public Timestamp value5() {
        return getEtime();
    }

    @Override
    public String value6() {
        return getReason();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public Integer value8() {
        return getResult();
    }

    @Override
    public String value9() {
        return getRemark();
    }

    @Override
    public Integer value10() {
        return getRole();
    }

    @Override
    public Integer value11() {
        return getTid();
    }

    @Override
    public LeaveRecord value1(Integer value) {
        setLid(value);
        return this;
    }

    @Override
    public LeaveRecord value2(Integer value) {
        setNid(value);
        return this;
    }

    @Override
    public LeaveRecord value3(Timestamp value) {
        setNtime(value);
        return this;
    }

    @Override
    public LeaveRecord value4(Timestamp value) {
        setStime(value);
        return this;
    }

    @Override
    public LeaveRecord value5(Timestamp value) {
        setEtime(value);
        return this;
    }

    @Override
    public LeaveRecord value6(String value) {
        setReason(value);
        return this;
    }

    @Override
    public LeaveRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public LeaveRecord value8(Integer value) {
        setResult(value);
        return this;
    }

    @Override
    public LeaveRecord value9(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public LeaveRecord value10(Integer value) {
        setRole(value);
        return this;
    }

    @Override
    public LeaveRecord value11(Integer value) {
        setTid(value);
        return this;
    }

    @Override
    public LeaveRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4, Timestamp value5, String value6, String value7, Integer value8, String value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeaveRecord
     */
    public LeaveRecord() {
        super(Leave.LEAVE);
    }

    /**
     * Create a detached, initialised LeaveRecord
     */
    public LeaveRecord(Integer lid, Integer nid, Timestamp ntime, Timestamp stime, Timestamp etime, String reason, String type, Integer result, String remark, Integer role, Integer tid) {
        super(Leave.LEAVE);

        set(0, lid);
        set(1, nid);
        set(2, ntime);
        set(3, stime);
        set(4, etime);
        set(5, reason);
        set(6, type);
        set(7, result);
        set(8, remark);
        set(9, role);
        set(10, tid);
    }
}
