/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.records;


import com.heman.bysj.jooq.tables.Student;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record12<Integer, String, String, String, String, Integer, String, String, String, Integer, String, String> {

    private static final long serialVersionUID = -378123256;

    /**
     * Setter for <code>bysj.student.sid</code>. 主键ID
     */
    public void setSid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bysj.student.sid</code>. 主键ID
     */
    public Integer getSid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bysj.student.name</code>. 学生姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bysj.student.name</code>. 学生姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bysj.student.sex</code>. 性别：女，男
     */
    public void setSex(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bysj.student.sex</code>. 性别：女，男
     */
    public String getSex() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bysj.student.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bysj.student.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bysj.student.password</code>. 密码
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bysj.student.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bysj.student.grade</code>. 年级
     */
    public void setGrade(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bysj.student.grade</code>. 年级
     */
    public Integer getGrade() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bysj.student.profession</code>. 专业
     */
    public void setProfession(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bysj.student.profession</code>. 专业
     */
    public String getProfession() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bysj.student.college</code>. 所在学院
     */
    public void setCollege(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bysj.student.college</code>. 所在学院
     */
    public String getCollege() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bysj.student.class_</code>. 班级
     */
    public void setClass_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bysj.student.class_</code>. 班级
     */
    public String getClass_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bysj.student.tid</code>. 辅导教师
     */
    public void setTid(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bysj.student.tid</code>. 辅导教师
     */
    public Integer getTid() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>bysj.student.role</code>. 角色：学生
     */
    public void setRole(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>bysj.student.role</code>. 角色：学生
     */
    public String getRole() {
        return (String) get(10);
    }

    /**
     * Setter for <code>bysj.student.group</code>. 所属组用户：Group_Student
     */
    public void setGroup(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bysj.student.group</code>. 所属组用户：Group_Student
     */
    public String getGroup() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, String, String, Integer, String, String, String, Integer, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, String, String, Integer, String, String, String, Integer, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.SID;
    }

    @Override
    public Field<String> field2() {
        return Student.STUDENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Student.STUDENT.SEX;
    }

    @Override
    public Field<String> field4() {
        return Student.STUDENT.USERNAME;
    }

    @Override
    public Field<String> field5() {
        return Student.STUDENT.PASSWORD;
    }

    @Override
    public Field<Integer> field6() {
        return Student.STUDENT.GRADE;
    }

    @Override
    public Field<String> field7() {
        return Student.STUDENT.PROFESSION;
    }

    @Override
    public Field<String> field8() {
        return Student.STUDENT.COLLEGE;
    }

    @Override
    public Field<String> field9() {
        return Student.STUDENT.CLASS_;
    }

    @Override
    public Field<Integer> field10() {
        return Student.STUDENT.TID;
    }

    @Override
    public Field<String> field11() {
        return Student.STUDENT.ROLE;
    }

    @Override
    public Field<String> field12() {
        return Student.STUDENT.GROUP;
    }

    @Override
    public Integer component1() {
        return getSid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSex();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public Integer component6() {
        return getGrade();
    }

    @Override
    public String component7() {
        return getProfession();
    }

    @Override
    public String component8() {
        return getCollege();
    }

    @Override
    public String component9() {
        return getClass_();
    }

    @Override
    public Integer component10() {
        return getTid();
    }

    @Override
    public String component11() {
        return getRole();
    }

    @Override
    public String component12() {
        return getGroup();
    }

    @Override
    public Integer value1() {
        return getSid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSex();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public Integer value6() {
        return getGrade();
    }

    @Override
    public String value7() {
        return getProfession();
    }

    @Override
    public String value8() {
        return getCollege();
    }

    @Override
    public String value9() {
        return getClass_();
    }

    @Override
    public Integer value10() {
        return getTid();
    }

    @Override
    public String value11() {
        return getRole();
    }

    @Override
    public String value12() {
        return getGroup();
    }

    @Override
    public StudentRecord value1(Integer value) {
        setSid(value);
        return this;
    }

    @Override
    public StudentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StudentRecord value3(String value) {
        setSex(value);
        return this;
    }

    @Override
    public StudentRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public StudentRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public StudentRecord value6(Integer value) {
        setGrade(value);
        return this;
    }

    @Override
    public StudentRecord value7(String value) {
        setProfession(value);
        return this;
    }

    @Override
    public StudentRecord value8(String value) {
        setCollege(value);
        return this;
    }

    @Override
    public StudentRecord value9(String value) {
        setClass_(value);
        return this;
    }

    @Override
    public StudentRecord value10(Integer value) {
        setTid(value);
        return this;
    }

    @Override
    public StudentRecord value11(String value) {
        setRole(value);
        return this;
    }

    @Override
    public StudentRecord value12(String value) {
        setGroup(value);
        return this;
    }

    @Override
    public StudentRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, Integer value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer sid, String name, String sex, String username, String password, Integer grade, String profession, String college, String class_, Integer tid, String role, String group) {
        super(Student.STUDENT);

        set(0, sid);
        set(1, name);
        set(2, sex);
        set(3, username);
        set(4, password);
        set(5, grade);
        set(6, profession);
        set(7, college);
        set(8, class_);
        set(9, tid);
        set(10, role);
        set(11, group);
    }
}
