/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq;


import com.heman.bysj.jooq.tables.Leave;
import com.heman.bysj.jooq.tables.Student;
import com.heman.bysj.jooq.tables.Teacher;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bysj extends SchemaImpl {

    private static final long serialVersionUID = 1141920378;

    /**
     * The reference instance of <code>bysj</code>
     */
    public static final Bysj BYSJ = new Bysj();

    /**
     * The table <code>bysj.leave</code>.
     */
    public final Leave LEAVE = com.heman.bysj.jooq.tables.Leave.LEAVE;

    /**
     * The table <code>bysj.student</code>.
     */
    public final Student STUDENT = com.heman.bysj.jooq.tables.Student.STUDENT;

    /**
     * The table <code>bysj.teacher</code>.
     */
    public final Teacher TEACHER = com.heman.bysj.jooq.tables.Teacher.TEACHER;

    /**
     * No further instances allowed
     */
    private Bysj() {
        super("bysj", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Leave.LEAVE,
            Student.STUDENT,
            Teacher.TEACHER);
    }
}
