/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq;


import com.heman.bysj.jooq.tables.Leave;
import com.heman.bysj.jooq.tables.Student;
import com.heman.bysj.jooq.tables.Teacher;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bysj</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LEAVE_NID_KEY = Indexes0.LEAVE_NID_KEY;
    public static final Index LEAVE_PRIMARY = Indexes0.LEAVE_PRIMARY;
    public static final Index LEAVE_TID_KEY = Indexes0.LEAVE_TID_KEY;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index STUDENT_STUDENT_TID_FORIENGINKEY = Indexes0.STUDENT_STUDENT_TID_FORIENGINKEY;
    public static final Index STUDENT_SUSERNAME_UNIQUE = Indexes0.STUDENT_SUSERNAME_UNIQUE;
    public static final Index TEACHER_PRIMARY = Indexes0.TEACHER_PRIMARY;
    public static final Index TEACHER_TEACHER_SUPERIOR_KEY = Indexes0.TEACHER_TEACHER_SUPERIOR_KEY;
    public static final Index TEACHER_TUSERNAME_UNIQUE = Indexes0.TEACHER_TUSERNAME_UNIQUE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LEAVE_NID_KEY = Internal.createIndex("nid_key", Leave.LEAVE, new OrderField[] { Leave.LEAVE.NID }, false);
        public static Index LEAVE_PRIMARY = Internal.createIndex("PRIMARY", Leave.LEAVE, new OrderField[] { Leave.LEAVE.LID }, true);
        public static Index LEAVE_TID_KEY = Internal.createIndex("tid_key", Leave.LEAVE, new OrderField[] { Leave.LEAVE.TID }, false);
        public static Index STUDENT_PRIMARY = Internal.createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.SID }, true);
        public static Index STUDENT_STUDENT_TID_FORIENGINKEY = Internal.createIndex("student_tid_forienginkey", Student.STUDENT, new OrderField[] { Student.STUDENT.TID }, false);
        public static Index STUDENT_SUSERNAME_UNIQUE = Internal.createIndex("susername_unique", Student.STUDENT, new OrderField[] { Student.STUDENT.USERNAME }, true);
        public static Index TEACHER_PRIMARY = Internal.createIndex("PRIMARY", Teacher.TEACHER, new OrderField[] { Teacher.TEACHER.TID }, true);
        public static Index TEACHER_TEACHER_SUPERIOR_KEY = Internal.createIndex("teacher_superior_key", Teacher.TEACHER, new OrderField[] { Teacher.TEACHER.SUPERIOR }, false);
        public static Index TEACHER_TUSERNAME_UNIQUE = Internal.createIndex("tusername_unique", Teacher.TEACHER, new OrderField[] { Teacher.TEACHER.USERNAME }, true);
    }
}
