#端口
server:
  port: 8181

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bysj?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 980805
    driver-class-name: com.mysql.jdbc.Driver


#logging.level.com.heman.bysj.jooqService=debug
logging:
  file:
    name: logs.log