/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdMembership implements Serializable {

    private static final long serialVersionUID = -293466258;

    private String userId_;
    private String groupId_;

    public ActIdMembership() {}

    public ActIdMembership(ActIdMembership value) {
        this.userId_ = value.userId_;
        this.groupId_ = value.groupId_;
    }

    public ActIdMembership(
        String userId_,
        String groupId_
    ) {
        this.userId_ = userId_;
        this.groupId_ = groupId_;
    }

    public String getUserId_() {
        return this.userId_;
    }

    public void setUserId_(String userId_) {
        this.userId_ = userId_;
    }

    public String getGroupId_() {
        return this.groupId_;
    }

    public void setGroupId_(String groupId_) {
        this.groupId_ = groupId_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActIdMembership (");

        sb.append(userId_);
        sb.append(", ").append(groupId_);

        sb.append(")");
        return sb.toString();
    }
}
