/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdGroup implements Serializable {

    private static final long serialVersionUID = -81577841;

    private String  id_;
    private Integer rev_;
    private String  name_;
    private String  type_;

    public ActIdGroup() {}

    public ActIdGroup(ActIdGroup value) {
        this.id_ = value.id_;
        this.rev_ = value.rev_;
        this.name_ = value.name_;
        this.type_ = value.type_;
    }

    public ActIdGroup(
        String  id_,
        Integer rev_,
        String  name_,
        String  type_
    ) {
        this.id_ = id_;
        this.rev_ = rev_;
        this.name_ = name_;
        this.type_ = type_;
    }

    public String getId_() {
        return this.id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public Integer getRev_() {
        return this.rev_;
    }

    public void setRev_(Integer rev_) {
        this.rev_ = rev_;
    }

    public String getName_() {
        return this.name_;
    }

    public void setName_(String name_) {
        this.name_ = name_;
    }

    public String getType_() {
        return this.type_;
    }

    public void setType_(String type_) {
        this.type_ = type_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActIdGroup (");

        sb.append(id_);
        sb.append(", ").append(rev_);
        sb.append(", ").append(name_);
        sb.append(", ").append(type_);

        sb.append(")");
        return sb.toString();
    }
}
