/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Changemajors implements Serializable {

    private static final long serialVersionUID = -1850063748;

    private String    cid;
    private String    processinstanceid;
    private Integer   userid;
    private String    reason;
    private String    currentcollege;
    private String    currentprofession;
    private String    currentclass;
    private String    newcollege;
    private String    newprofession;
    private Double    gpa;
    private String    rank;
    private String    contest;
    private Integer   processstatus;
    private Timestamp createtime;
    private Timestamp updatetime;

    public Changemajors() {}

    public Changemajors(Changemajors value) {
        this.cid = value.cid;
        this.processinstanceid = value.processinstanceid;
        this.userid = value.userid;
        this.reason = value.reason;
        this.currentcollege = value.currentcollege;
        this.currentprofession = value.currentprofession;
        this.currentclass = value.currentclass;
        this.newcollege = value.newcollege;
        this.newprofession = value.newprofession;
        this.gpa = value.gpa;
        this.rank = value.rank;
        this.contest = value.contest;
        this.processstatus = value.processstatus;
        this.createtime = value.createtime;
        this.updatetime = value.updatetime;
    }

    public Changemajors(
        String    cid,
        String    processinstanceid,
        Integer   userid,
        String    reason,
        String    currentcollege,
        String    currentprofession,
        String    currentclass,
        String    newcollege,
        String    newprofession,
        Double    gpa,
        String    rank,
        String    contest,
        Integer   processstatus,
        Timestamp createtime,
        Timestamp updatetime
    ) {
        this.cid = cid;
        this.processinstanceid = processinstanceid;
        this.userid = userid;
        this.reason = reason;
        this.currentcollege = currentcollege;
        this.currentprofession = currentprofession;
        this.currentclass = currentclass;
        this.newcollege = newcollege;
        this.newprofession = newprofession;
        this.gpa = gpa;
        this.rank = rank;
        this.contest = contest;
        this.processstatus = processstatus;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    public String getCid() {
        return this.cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getProcessinstanceid() {
        return this.processinstanceid;
    }

    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getCurrentcollege() {
        return this.currentcollege;
    }

    public void setCurrentcollege(String currentcollege) {
        this.currentcollege = currentcollege;
    }

    public String getCurrentprofession() {
        return this.currentprofession;
    }

    public void setCurrentprofession(String currentprofession) {
        this.currentprofession = currentprofession;
    }

    public String getCurrentclass() {
        return this.currentclass;
    }

    public void setCurrentclass(String currentclass) {
        this.currentclass = currentclass;
    }

    public String getNewcollege() {
        return this.newcollege;
    }

    public void setNewcollege(String newcollege) {
        this.newcollege = newcollege;
    }

    public String getNewprofession() {
        return this.newprofession;
    }

    public void setNewprofession(String newprofession) {
        this.newprofession = newprofession;
    }

    public Double getGpa() {
        return this.gpa;
    }

    public void setGpa(Double gpa) {
        this.gpa = gpa;
    }

    public String getRank() {
        return this.rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public String getContest() {
        return this.contest;
    }

    public void setContest(String contest) {
        this.contest = contest;
    }

    public Integer getProcessstatus() {
        return this.processstatus;
    }

    public void setProcessstatus(Integer processstatus) {
        this.processstatus = processstatus;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    public Timestamp getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Timestamp updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Changemajors (");

        sb.append(cid);
        sb.append(", ").append(processinstanceid);
        sb.append(", ").append(userid);
        sb.append(", ").append(reason);
        sb.append(", ").append(currentcollege);
        sb.append(", ").append(currentprofession);
        sb.append(", ").append(currentclass);
        sb.append(", ").append(newcollege);
        sb.append(", ").append(newprofession);
        sb.append(", ").append(gpa);
        sb.append(", ").append(rank);
        sb.append(", ").append(contest);
        sb.append(", ").append(processstatus);
        sb.append(", ").append(createtime);
        sb.append(", ").append(updatetime);

        sb.append(")");
        return sb.toString();
    }
}
