/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classes implements Serializable {

    private static final long serialVersionUID = 555184861;

    private Integer id;
    private String  college;
    private String  profession;
    private String  class_;

    public Classes() {}

    public Classes(Classes value) {
        this.id = value.id;
        this.college = value.college;
        this.profession = value.profession;
        this.class_ = value.class_;
    }

    public Classes(
        Integer id,
        String  college,
        String  profession,
        String  class_
    ) {
        this.id = id;
        this.college = college;
        this.profession = profession;
        this.class_ = class_;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCollege() {
        return this.college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public String getProfession() {
        return this.profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Classes (");

        sb.append(id);
        sb.append(", ").append(college);
        sb.append(", ").append(profession);
        sb.append(", ").append(class_);

        sb.append(")");
        return sb.toString();
    }
}
