/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examine implements Serializable {

    private static final long serialVersionUID = -1782426060;

    private String    checkid;
    private String    processinstanceid;
    private String    taskid;
    private Integer   userid;
    private String    role;
    private String    checkresult;
    private String    opinion;
    private Timestamp checktime;

    public Examine() {}

    public Examine(Examine value) {
        this.checkid = value.checkid;
        this.processinstanceid = value.processinstanceid;
        this.taskid = value.taskid;
        this.userid = value.userid;
        this.role = value.role;
        this.checkresult = value.checkresult;
        this.opinion = value.opinion;
        this.checktime = value.checktime;
    }

    public Examine(
        String    checkid,
        String    processinstanceid,
        String    taskid,
        Integer   userid,
        String    role,
        String    checkresult,
        String    opinion,
        Timestamp checktime
    ) {
        this.checkid = checkid;
        this.processinstanceid = processinstanceid;
        this.taskid = taskid;
        this.userid = userid;
        this.role = role;
        this.checkresult = checkresult;
        this.opinion = opinion;
        this.checktime = checktime;
    }

    public String getCheckid() {
        return this.checkid;
    }

    public void setCheckid(String checkid) {
        this.checkid = checkid;
    }

    public String getProcessinstanceid() {
        return this.processinstanceid;
    }

    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    public String getTaskid() {
        return this.taskid;
    }

    public void setTaskid(String taskid) {
        this.taskid = taskid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getCheckresult() {
        return this.checkresult;
    }

    public void setCheckresult(String checkresult) {
        this.checkresult = checkresult;
    }

    public String getOpinion() {
        return this.opinion;
    }

    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    public Timestamp getChecktime() {
        return this.checktime;
    }

    public void setChecktime(Timestamp checktime) {
        this.checktime = checktime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Examine (");

        sb.append(checkid);
        sb.append(", ").append(processinstanceid);
        sb.append(", ").append(taskid);
        sb.append(", ").append(userid);
        sb.append(", ").append(role);
        sb.append(", ").append(checkresult);
        sb.append(", ").append(opinion);
        sb.append(", ").append(checktime);

        sb.append(")");
        return sb.toString();
    }
}
