/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Majorapproval implements Serializable {

    private static final long serialVersionUID = -1264893753;

    private Integer aid;
    private Integer cid;
    private String  currentacademicoffice;
    private String  caresult;
    private String  careason;
    private String  currentdean;
    private String  cdresult;
    private String  cdreason;
    private String  newacademicoffice;
    private String  naresult;
    private String  nareason;
    private String  newdean;
    private String  ndresult;
    private String  ndreason;
    private String  academicoffice;
    private String  aoresult;
    private String  aoreason;
    private Integer state;

    public Majorapproval() {}

    public Majorapproval(Majorapproval value) {
        this.aid = value.aid;
        this.cid = value.cid;
        this.currentacademicoffice = value.currentacademicoffice;
        this.caresult = value.caresult;
        this.careason = value.careason;
        this.currentdean = value.currentdean;
        this.cdresult = value.cdresult;
        this.cdreason = value.cdreason;
        this.newacademicoffice = value.newacademicoffice;
        this.naresult = value.naresult;
        this.nareason = value.nareason;
        this.newdean = value.newdean;
        this.ndresult = value.ndresult;
        this.ndreason = value.ndreason;
        this.academicoffice = value.academicoffice;
        this.aoresult = value.aoresult;
        this.aoreason = value.aoreason;
        this.state = value.state;
    }

    public Majorapproval(
        Integer aid,
        Integer cid,
        String  currentacademicoffice,
        String  caresult,
        String  careason,
        String  currentdean,
        String  cdresult,
        String  cdreason,
        String  newacademicoffice,
        String  naresult,
        String  nareason,
        String  newdean,
        String  ndresult,
        String  ndreason,
        String  academicoffice,
        String  aoresult,
        String  aoreason,
        Integer state
    ) {
        this.aid = aid;
        this.cid = cid;
        this.currentacademicoffice = currentacademicoffice;
        this.caresult = caresult;
        this.careason = careason;
        this.currentdean = currentdean;
        this.cdresult = cdresult;
        this.cdreason = cdreason;
        this.newacademicoffice = newacademicoffice;
        this.naresult = naresult;
        this.nareason = nareason;
        this.newdean = newdean;
        this.ndresult = ndresult;
        this.ndreason = ndreason;
        this.academicoffice = academicoffice;
        this.aoresult = aoresult;
        this.aoreason = aoreason;
        this.state = state;
    }

    public Integer getAid() {
        return this.aid;
    }

    public void setAid(Integer aid) {
        this.aid = aid;
    }

    public Integer getCid() {
        return this.cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public String getCurrentacademicoffice() {
        return this.currentacademicoffice;
    }

    public void setCurrentacademicoffice(String currentacademicoffice) {
        this.currentacademicoffice = currentacademicoffice;
    }

    public String getCaresult() {
        return this.caresult;
    }

    public void setCaresult(String caresult) {
        this.caresult = caresult;
    }

    public String getCareason() {
        return this.careason;
    }

    public void setCareason(String careason) {
        this.careason = careason;
    }

    public String getCurrentdean() {
        return this.currentdean;
    }

    public void setCurrentdean(String currentdean) {
        this.currentdean = currentdean;
    }

    public String getCdresult() {
        return this.cdresult;
    }

    public void setCdresult(String cdresult) {
        this.cdresult = cdresult;
    }

    public String getCdreason() {
        return this.cdreason;
    }

    public void setCdreason(String cdreason) {
        this.cdreason = cdreason;
    }

    public String getNewacademicoffice() {
        return this.newacademicoffice;
    }

    public void setNewacademicoffice(String newacademicoffice) {
        this.newacademicoffice = newacademicoffice;
    }

    public String getNaresult() {
        return this.naresult;
    }

    public void setNaresult(String naresult) {
        this.naresult = naresult;
    }

    public String getNareason() {
        return this.nareason;
    }

    public void setNareason(String nareason) {
        this.nareason = nareason;
    }

    public String getNewdean() {
        return this.newdean;
    }

    public void setNewdean(String newdean) {
        this.newdean = newdean;
    }

    public String getNdresult() {
        return this.ndresult;
    }

    public void setNdresult(String ndresult) {
        this.ndresult = ndresult;
    }

    public String getNdreason() {
        return this.ndreason;
    }

    public void setNdreason(String ndreason) {
        this.ndreason = ndreason;
    }

    public String getAcademicoffice() {
        return this.academicoffice;
    }

    public void setAcademicoffice(String academicoffice) {
        this.academicoffice = academicoffice;
    }

    public String getAoresult() {
        return this.aoresult;
    }

    public void setAoresult(String aoresult) {
        this.aoresult = aoresult;
    }

    public String getAoreason() {
        return this.aoreason;
    }

    public void setAoreason(String aoreason) {
        this.aoreason = aoreason;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Majorapproval (");

        sb.append(aid);
        sb.append(", ").append(cid);
        sb.append(", ").append(currentacademicoffice);
        sb.append(", ").append(caresult);
        sb.append(", ").append(careason);
        sb.append(", ").append(currentdean);
        sb.append(", ").append(cdresult);
        sb.append(", ").append(cdreason);
        sb.append(", ").append(newacademicoffice);
        sb.append(", ").append(naresult);
        sb.append(", ").append(nareason);
        sb.append(", ").append(newdean);
        sb.append(", ").append(ndresult);
        sb.append(", ").append(ndreason);
        sb.append(", ").append(academicoffice);
        sb.append(", ").append(aoresult);
        sb.append(", ").append(aoreason);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
