/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Project implements Serializable {

    private static final long serialVersionUID = 913412278;

    private String    formid;
    private String    processinstanceid;
    private Integer   userid;
    private String    role;
    private String    projectname;
    private String    context;
    private String    mean;
    private String    result;
    private Double    fund;
    private String    funditem;
    private Integer   processstatus;
    private Timestamp createtime;
    private Timestamp updatetime;

    public Project() {}

    public Project(Project value) {
        this.formid = value.formid;
        this.processinstanceid = value.processinstanceid;
        this.userid = value.userid;
        this.role = value.role;
        this.projectname = value.projectname;
        this.context = value.context;
        this.mean = value.mean;
        this.result = value.result;
        this.fund = value.fund;
        this.funditem = value.funditem;
        this.processstatus = value.processstatus;
        this.createtime = value.createtime;
        this.updatetime = value.updatetime;
    }

    public Project(
        String    formid,
        String    processinstanceid,
        Integer   userid,
        String    role,
        String    projectname,
        String    context,
        String    mean,
        String    result,
        Double    fund,
        String    funditem,
        Integer   processstatus,
        Timestamp createtime,
        Timestamp updatetime
    ) {
        this.formid = formid;
        this.processinstanceid = processinstanceid;
        this.userid = userid;
        this.role = role;
        this.projectname = projectname;
        this.context = context;
        this.mean = mean;
        this.result = result;
        this.fund = fund;
        this.funditem = funditem;
        this.processstatus = processstatus;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    public String getFormid() {
        return this.formid;
    }

    public void setFormid(String formid) {
        this.formid = formid;
    }

    public String getProcessinstanceid() {
        return this.processinstanceid;
    }

    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getProjectname() {
        return this.projectname;
    }

    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    public String getContext() {
        return this.context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public String getMean() {
        return this.mean;
    }

    public void setMean(String mean) {
        this.mean = mean;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Double getFund() {
        return this.fund;
    }

    public void setFund(Double fund) {
        this.fund = fund;
    }

    public String getFunditem() {
        return this.funditem;
    }

    public void setFunditem(String funditem) {
        this.funditem = funditem;
    }

    public Integer getProcessstatus() {
        return this.processstatus;
    }

    public void setProcessstatus(Integer processstatus) {
        this.processstatus = processstatus;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    public Timestamp getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Timestamp updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Project (");

        sb.append(formid);
        sb.append(", ").append(processinstanceid);
        sb.append(", ").append(userid);
        sb.append(", ").append(role);
        sb.append(", ").append(projectname);
        sb.append(", ").append(context);
        sb.append(", ").append(mean);
        sb.append(", ").append(result);
        sb.append(", ").append(fund);
        sb.append(", ").append(funditem);
        sb.append(", ").append(processstatus);
        sb.append(", ").append(createtime);
        sb.append(", ").append(updatetime);

        sb.append(")");
        return sb.toString();
    }
}
