/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActHiVarinstRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiVarinst extends TableImpl<ActHiVarinstRecord> {

    private static final long serialVersionUID = -1465764470;

    /**
     * The reference instance of <code>bysj.act_hi_varinst</code>
     */
    public static final ActHiVarinst ACT_HI_VARINST = new ActHiVarinst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActHiVarinstRecord> getRecordType() {
        return ActHiVarinstRecord.class;
    }

    /**
     * The column <code>bysj.act_hi_varinst.ID_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.PROC_INST_ID_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> PROC_INST_ID_ = createField(DSL.name("PROC_INST_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.EXECUTION_ID_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> EXECUTION_ID_ = createField(DSL.name("EXECUTION_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.TASK_ID_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> TASK_ID_ = createField(DSL.name("TASK_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.NAME_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> NAME_ = createField(DSL.name("NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.VAR_TYPE_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> VAR_TYPE_ = createField(DSL.name("VAR_TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.REV_</code>.
     */
    public final TableField<ActHiVarinstRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_hi_varinst.BYTEARRAY_ID_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> BYTEARRAY_ID_ = createField(DSL.name("BYTEARRAY_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.DOUBLE_</code>.
     */
    public final TableField<ActHiVarinstRecord, Double> DOUBLE_ = createField(DSL.name("DOUBLE_"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>bysj.act_hi_varinst.LONG_</code>.
     */
    public final TableField<ActHiVarinstRecord, Long> LONG_ = createField(DSL.name("LONG_"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bysj.act_hi_varinst.TEXT_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> TEXT_ = createField(DSL.name("TEXT_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.TEXT2_</code>.
     */
    public final TableField<ActHiVarinstRecord, String> TEXT2_ = createField(DSL.name("TEXT2_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_hi_varinst.CREATE_TIME_</code>.
     */
    public final TableField<ActHiVarinstRecord, Timestamp> CREATE_TIME_ = createField(DSL.name("CREATE_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_hi_varinst.LAST_UPDATED_TIME_</code>.
     */
    public final TableField<ActHiVarinstRecord, Timestamp> LAST_UPDATED_TIME_ = createField(DSL.name("LAST_UPDATED_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>bysj.act_hi_varinst</code> table reference
     */
    public ActHiVarinst() {
        this(DSL.name("act_hi_varinst"), null);
    }

    /**
     * Create an aliased <code>bysj.act_hi_varinst</code> table reference
     */
    public ActHiVarinst(String alias) {
        this(DSL.name(alias), ACT_HI_VARINST);
    }

    /**
     * Create an aliased <code>bysj.act_hi_varinst</code> table reference
     */
    public ActHiVarinst(Name alias) {
        this(alias, ACT_HI_VARINST);
    }

    private ActHiVarinst(Name alias, Table<ActHiVarinstRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActHiVarinst(Name alias, Table<ActHiVarinstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActHiVarinst(Table<O> child, ForeignKey<O, ActHiVarinstRecord> key) {
        super(child, key, ACT_HI_VARINST);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_HI_VARINST_ACT_IDX_HI_PROCVAR_NAME_TYPE, Indexes.ACT_HI_VARINST_ACT_IDX_HI_PROCVAR_PROC_INST, Indexes.ACT_HI_VARINST_ACT_IDX_HI_PROCVAR_TASK_ID, Indexes.ACT_HI_VARINST_PRIMARY);
    }

    @Override
    public UniqueKey<ActHiVarinstRecord> getPrimaryKey() {
        return Keys.KEY_ACT_HI_VARINST_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActHiVarinstRecord>> getKeys() {
        return Arrays.<UniqueKey<ActHiVarinstRecord>>asList(Keys.KEY_ACT_HI_VARINST_PRIMARY);
    }

    @Override
    public ActHiVarinst as(String alias) {
        return new ActHiVarinst(DSL.name(alias), this);
    }

    @Override
    public ActHiVarinst as(Name alias) {
        return new ActHiVarinst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiVarinst rename(String name) {
        return new ActHiVarinst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiVarinst rename(Name name) {
        return new ActHiVarinst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, String, String, String, Integer, String, Double, Long, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
