/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActHiActinstRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiActinst extends TableImpl<ActHiActinstRecord> {

    private static final long serialVersionUID = -1086933344;

    /**
     * The reference instance of <code>bysj.act_hi_actinst</code>
     */
    public static final ActHiActinst ACT_HI_ACTINST = new ActHiActinst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActHiActinstRecord> getRecordType() {
        return ActHiActinstRecord.class;
    }

    /**
     * The column <code>bysj.act_hi_actinst.ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.PROC_DEF_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> PROC_DEF_ID_ = createField(DSL.name("PROC_DEF_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.PROC_INST_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> PROC_INST_ID_ = createField(DSL.name("PROC_INST_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.EXECUTION_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> EXECUTION_ID_ = createField(DSL.name("EXECUTION_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.ACT_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> ACT_ID_ = createField(DSL.name("ACT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.TASK_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> TASK_ID_ = createField(DSL.name("TASK_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.CALL_PROC_INST_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> CALL_PROC_INST_ID_ = createField(DSL.name("CALL_PROC_INST_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.ACT_NAME_</code>.
     */
    public final TableField<ActHiActinstRecord, String> ACT_NAME_ = createField(DSL.name("ACT_NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.ACT_TYPE_</code>.
     */
    public final TableField<ActHiActinstRecord, String> ACT_TYPE_ = createField(DSL.name("ACT_TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.ASSIGNEE_</code>.
     */
    public final TableField<ActHiActinstRecord, String> ASSIGNEE_ = createField(DSL.name("ASSIGNEE_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.START_TIME_</code>.
     */
    public final TableField<ActHiActinstRecord, Timestamp> START_TIME_ = createField(DSL.name("START_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.END_TIME_</code>.
     */
    public final TableField<ActHiActinstRecord, Timestamp> END_TIME_ = createField(DSL.name("END_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_hi_actinst.DURATION_</code>.
     */
    public final TableField<ActHiActinstRecord, Long> DURATION_ = createField(DSL.name("DURATION_"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bysj.act_hi_actinst.DELETE_REASON_</code>.
     */
    public final TableField<ActHiActinstRecord, String> DELETE_REASON_ = createField(DSL.name("DELETE_REASON_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_hi_actinst.TENANT_ID_</code>.
     */
    public final TableField<ActHiActinstRecord, String> TENANT_ID_ = createField(DSL.name("TENANT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>bysj.act_hi_actinst</code> table reference
     */
    public ActHiActinst() {
        this(DSL.name("act_hi_actinst"), null);
    }

    /**
     * Create an aliased <code>bysj.act_hi_actinst</code> table reference
     */
    public ActHiActinst(String alias) {
        this(DSL.name(alias), ACT_HI_ACTINST);
    }

    /**
     * Create an aliased <code>bysj.act_hi_actinst</code> table reference
     */
    public ActHiActinst(Name alias) {
        this(alias, ACT_HI_ACTINST);
    }

    private ActHiActinst(Name alias, Table<ActHiActinstRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActHiActinst(Name alias, Table<ActHiActinstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActHiActinst(Table<O> child, ForeignKey<O, ActHiActinstRecord> key) {
        super(child, key, ACT_HI_ACTINST);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_HI_ACTINST_ACT_IDX_HI_ACT_INST_END, Indexes.ACT_HI_ACTINST_ACT_IDX_HI_ACT_INST_EXEC, Indexes.ACT_HI_ACTINST_ACT_IDX_HI_ACT_INST_PROCINST, Indexes.ACT_HI_ACTINST_ACT_IDX_HI_ACT_INST_START, Indexes.ACT_HI_ACTINST_PRIMARY);
    }

    @Override
    public UniqueKey<ActHiActinstRecord> getPrimaryKey() {
        return Keys.KEY_ACT_HI_ACTINST_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActHiActinstRecord>> getKeys() {
        return Arrays.<UniqueKey<ActHiActinstRecord>>asList(Keys.KEY_ACT_HI_ACTINST_PRIMARY);
    }

    @Override
    public ActHiActinst as(String alias) {
        return new ActHiActinst(DSL.name(alias), this);
    }

    @Override
    public ActHiActinst as(Name alias) {
        return new ActHiActinst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiActinst rename(String name) {
        return new ActHiActinst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiActinst rename(Name name) {
        return new ActHiActinst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Long, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
