/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActIdGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdGroup extends TableImpl<ActIdGroupRecord> {

    private static final long serialVersionUID = -1285017574;

    /**
     * The reference instance of <code>bysj.act_id_group</code>
     */
    public static final ActIdGroup ACT_ID_GROUP = new ActIdGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActIdGroupRecord> getRecordType() {
        return ActIdGroupRecord.class;
    }

    /**
     * The column <code>bysj.act_id_group.ID_</code>.
     */
    public final TableField<ActIdGroupRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_id_group.REV_</code>.
     */
    public final TableField<ActIdGroupRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_id_group.NAME_</code>.
     */
    public final TableField<ActIdGroupRecord, String> NAME_ = createField(DSL.name("NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_id_group.TYPE_</code>.
     */
    public final TableField<ActIdGroupRecord, String> TYPE_ = createField(DSL.name("TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>bysj.act_id_group</code> table reference
     */
    public ActIdGroup() {
        this(DSL.name("act_id_group"), null);
    }

    /**
     * Create an aliased <code>bysj.act_id_group</code> table reference
     */
    public ActIdGroup(String alias) {
        this(DSL.name(alias), ACT_ID_GROUP);
    }

    /**
     * Create an aliased <code>bysj.act_id_group</code> table reference
     */
    public ActIdGroup(Name alias) {
        this(alias, ACT_ID_GROUP);
    }

    private ActIdGroup(Name alias, Table<ActIdGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActIdGroup(Name alias, Table<ActIdGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActIdGroup(Table<O> child, ForeignKey<O, ActIdGroupRecord> key) {
        super(child, key, ACT_ID_GROUP);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_ID_GROUP_PRIMARY);
    }

    @Override
    public UniqueKey<ActIdGroupRecord> getPrimaryKey() {
        return Keys.KEY_ACT_ID_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActIdGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<ActIdGroupRecord>>asList(Keys.KEY_ACT_ID_GROUP_PRIMARY);
    }

    @Override
    public ActIdGroup as(String alias) {
        return new ActIdGroup(DSL.name(alias), this);
    }

    @Override
    public ActIdGroup as(Name alias) {
        return new ActIdGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActIdGroup rename(String name) {
        return new ActIdGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActIdGroup rename(Name name) {
        return new ActIdGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
