/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActProcdefInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActProcdefInfo extends TableImpl<ActProcdefInfoRecord> {

    private static final long serialVersionUID = -1449354740;

    /**
     * The reference instance of <code>bysj.act_procdef_info</code>
     */
    public static final ActProcdefInfo ACT_PROCDEF_INFO = new ActProcdefInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActProcdefInfoRecord> getRecordType() {
        return ActProcdefInfoRecord.class;
    }

    /**
     * The column <code>bysj.act_procdef_info.ID_</code>.
     */
    public final TableField<ActProcdefInfoRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_procdef_info.PROC_DEF_ID_</code>.
     */
    public final TableField<ActProcdefInfoRecord, String> PROC_DEF_ID_ = createField(DSL.name("PROC_DEF_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_procdef_info.REV_</code>.
     */
    public final TableField<ActProcdefInfoRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_procdef_info.INFO_JSON_ID_</code>.
     */
    public final TableField<ActProcdefInfoRecord, String> INFO_JSON_ID_ = createField(DSL.name("INFO_JSON_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * Create a <code>bysj.act_procdef_info</code> table reference
     */
    public ActProcdefInfo() {
        this(DSL.name("act_procdef_info"), null);
    }

    /**
     * Create an aliased <code>bysj.act_procdef_info</code> table reference
     */
    public ActProcdefInfo(String alias) {
        this(DSL.name(alias), ACT_PROCDEF_INFO);
    }

    /**
     * Create an aliased <code>bysj.act_procdef_info</code> table reference
     */
    public ActProcdefInfo(Name alias) {
        this(alias, ACT_PROCDEF_INFO);
    }

    private ActProcdefInfo(Name alias, Table<ActProcdefInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActProcdefInfo(Name alias, Table<ActProcdefInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActProcdefInfo(Table<O> child, ForeignKey<O, ActProcdefInfoRecord> key) {
        super(child, key, ACT_PROCDEF_INFO);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_PROCDEF_INFO_ACT_FK_INFO_JSON_BA, Indexes.ACT_PROCDEF_INFO_ACT_IDX_INFO_PROCDEF, Indexes.ACT_PROCDEF_INFO_ACT_UNIQ_INFO_PROCDEF, Indexes.ACT_PROCDEF_INFO_PRIMARY);
    }

    @Override
    public UniqueKey<ActProcdefInfoRecord> getPrimaryKey() {
        return Keys.KEY_ACT_PROCDEF_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActProcdefInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<ActProcdefInfoRecord>>asList(Keys.KEY_ACT_PROCDEF_INFO_PRIMARY, Keys.KEY_ACT_PROCDEF_INFO_ACT_UNIQ_INFO_PROCDEF);
    }

    @Override
    public List<ForeignKey<ActProcdefInfoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActProcdefInfoRecord, ?>>asList(Keys.ACT_FK_INFO_PROCDEF, Keys.ACT_FK_INFO_JSON_BA);
    }

    public ActReProcdef actReProcdef() {
        return new ActReProcdef(this, Keys.ACT_FK_INFO_PROCDEF);
    }

    public ActGeBytearray actGeBytearray() {
        return new ActGeBytearray(this, Keys.ACT_FK_INFO_JSON_BA);
    }

    @Override
    public ActProcdefInfo as(String alias) {
        return new ActProcdefInfo(DSL.name(alias), this);
    }

    @Override
    public ActProcdefInfo as(Name alias) {
        return new ActProcdefInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActProcdefInfo rename(String name) {
        return new ActProcdefInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActProcdefInfo rename(Name name) {
        return new ActProcdefInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
