/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActReModelRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReModel extends TableImpl<ActReModelRecord> {

    private static final long serialVersionUID = 238384506;

    /**
     * The reference instance of <code>bysj.act_re_model</code>
     */
    public static final ActReModel ACT_RE_MODEL = new ActReModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActReModelRecord> getRecordType() {
        return ActReModelRecord.class;
    }

    /**
     * The column <code>bysj.act_re_model.ID_</code>.
     */
    public final TableField<ActReModelRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_re_model.REV_</code>.
     */
    public final TableField<ActReModelRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_re_model.NAME_</code>.
     */
    public final TableField<ActReModelRecord, String> NAME_ = createField(DSL.name("NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_model.KEY_</code>.
     */
    public final TableField<ActReModelRecord, String> KEY_ = createField(DSL.name("KEY_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_model.CATEGORY_</code>.
     */
    public final TableField<ActReModelRecord, String> CATEGORY_ = createField(DSL.name("CATEGORY_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_model.CREATE_TIME_</code>.
     */
    public final TableField<ActReModelRecord, Timestamp> CREATE_TIME_ = createField(DSL.name("CREATE_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_re_model.LAST_UPDATE_TIME_</code>.
     */
    public final TableField<ActReModelRecord, Timestamp> LAST_UPDATE_TIME_ = createField(DSL.name("LAST_UPDATE_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_re_model.VERSION_</code>.
     */
    public final TableField<ActReModelRecord, Integer> VERSION_ = createField(DSL.name("VERSION_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_re_model.META_INFO_</code>.
     */
    public final TableField<ActReModelRecord, String> META_INFO_ = createField(DSL.name("META_INFO_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_re_model.DEPLOYMENT_ID_</code>.
     */
    public final TableField<ActReModelRecord, String> DEPLOYMENT_ID_ = createField(DSL.name("DEPLOYMENT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_re_model.EDITOR_SOURCE_VALUE_ID_</code>.
     */
    public final TableField<ActReModelRecord, String> EDITOR_SOURCE_VALUE_ID_ = createField(DSL.name("EDITOR_SOURCE_VALUE_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_</code>.
     */
    public final TableField<ActReModelRecord, String> EDITOR_SOURCE_EXTRA_VALUE_ID_ = createField(DSL.name("EDITOR_SOURCE_EXTRA_VALUE_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_re_model.TENANT_ID_</code>.
     */
    public final TableField<ActReModelRecord, String> TENANT_ID_ = createField(DSL.name("TENANT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>bysj.act_re_model</code> table reference
     */
    public ActReModel() {
        this(DSL.name("act_re_model"), null);
    }

    /**
     * Create an aliased <code>bysj.act_re_model</code> table reference
     */
    public ActReModel(String alias) {
        this(DSL.name(alias), ACT_RE_MODEL);
    }

    /**
     * Create an aliased <code>bysj.act_re_model</code> table reference
     */
    public ActReModel(Name alias) {
        this(alias, ACT_RE_MODEL);
    }

    private ActReModel(Name alias, Table<ActReModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActReModel(Name alias, Table<ActReModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActReModel(Table<O> child, ForeignKey<O, ActReModelRecord> key) {
        super(child, key, ACT_RE_MODEL);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_RE_MODEL_ACT_FK_MODEL_DEPLOYMENT, Indexes.ACT_RE_MODEL_ACT_FK_MODEL_SOURCE, Indexes.ACT_RE_MODEL_ACT_FK_MODEL_SOURCE_EXTRA, Indexes.ACT_RE_MODEL_PRIMARY);
    }

    @Override
    public UniqueKey<ActReModelRecord> getPrimaryKey() {
        return Keys.KEY_ACT_RE_MODEL_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActReModelRecord>> getKeys() {
        return Arrays.<UniqueKey<ActReModelRecord>>asList(Keys.KEY_ACT_RE_MODEL_PRIMARY);
    }

    @Override
    public List<ForeignKey<ActReModelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActReModelRecord, ?>>asList(Keys.ACT_FK_MODEL_DEPLOYMENT, Keys.ACT_FK_MODEL_SOURCE, Keys.ACT_FK_MODEL_SOURCE_EXTRA);
    }

    public ActReDeployment actReDeployment() {
        return new ActReDeployment(this, Keys.ACT_FK_MODEL_DEPLOYMENT);
    }

    public ActGeBytearray actFkModelSource() {
        return new ActGeBytearray(this, Keys.ACT_FK_MODEL_SOURCE);
    }

    public ActGeBytearray actFkModelSourceExtra() {
        return new ActGeBytearray(this, Keys.ACT_FK_MODEL_SOURCE_EXTRA);
    }

    @Override
    public ActReModel as(String alias) {
        return new ActReModel(DSL.name(alias), this);
    }

    @Override
    public ActReModel as(Name alias) {
        return new ActReModel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReModel rename(String name) {
        return new ActReModel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReModel rename(Name name) {
        return new ActReModel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, Integer, String, String, String, Timestamp, Timestamp, Integer, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
