/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActReDeploymentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReDeployment extends TableImpl<ActReDeploymentRecord> {

    private static final long serialVersionUID = -1179565429;

    /**
     * The reference instance of <code>bysj.act_re_deployment</code>
     */
    public static final ActReDeployment ACT_RE_DEPLOYMENT = new ActReDeployment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActReDeploymentRecord> getRecordType() {
        return ActReDeploymentRecord.class;
    }

    /**
     * The column <code>bysj.act_re_deployment.ID_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_re_deployment.NAME_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> NAME_ = createField(DSL.name("NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_deployment.CATEGORY_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> CATEGORY_ = createField(DSL.name("CATEGORY_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_deployment.KEY_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> KEY_ = createField(DSL.name("KEY_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_re_deployment.TENANT_ID_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> TENANT_ID_ = createField(DSL.name("TENANT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>bysj.act_re_deployment.DEPLOY_TIME_</code>.
     */
    public final TableField<ActReDeploymentRecord, Timestamp> DEPLOY_TIME_ = createField(DSL.name("DEPLOY_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_re_deployment.ENGINE_VERSION_</code>.
     */
    public final TableField<ActReDeploymentRecord, String> ENGINE_VERSION_ = createField(DSL.name("ENGINE_VERSION_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>bysj.act_re_deployment</code> table reference
     */
    public ActReDeployment() {
        this(DSL.name("act_re_deployment"), null);
    }

    /**
     * Create an aliased <code>bysj.act_re_deployment</code> table reference
     */
    public ActReDeployment(String alias) {
        this(DSL.name(alias), ACT_RE_DEPLOYMENT);
    }

    /**
     * Create an aliased <code>bysj.act_re_deployment</code> table reference
     */
    public ActReDeployment(Name alias) {
        this(alias, ACT_RE_DEPLOYMENT);
    }

    private ActReDeployment(Name alias, Table<ActReDeploymentRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActReDeployment(Name alias, Table<ActReDeploymentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActReDeployment(Table<O> child, ForeignKey<O, ActReDeploymentRecord> key) {
        super(child, key, ACT_RE_DEPLOYMENT);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_RE_DEPLOYMENT_PRIMARY);
    }

    @Override
    public UniqueKey<ActReDeploymentRecord> getPrimaryKey() {
        return Keys.KEY_ACT_RE_DEPLOYMENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActReDeploymentRecord>> getKeys() {
        return Arrays.<UniqueKey<ActReDeploymentRecord>>asList(Keys.KEY_ACT_RE_DEPLOYMENT_PRIMARY);
    }

    @Override
    public ActReDeployment as(String alias) {
        return new ActReDeployment(DSL.name(alias), this);
    }

    @Override
    public ActReDeployment as(Name alias) {
        return new ActReDeployment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReDeployment rename(String name) {
        return new ActReDeployment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReDeployment rename(Name name) {
        return new ActReDeployment(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
