/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActRuVariableRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuVariable extends TableImpl<ActRuVariableRecord> {

    private static final long serialVersionUID = -1242739799;

    /**
     * The reference instance of <code>bysj.act_ru_variable</code>
     */
    public static final ActRuVariable ACT_RU_VARIABLE = new ActRuVariable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActRuVariableRecord> getRecordType() {
        return ActRuVariableRecord.class;
    }

    /**
     * The column <code>bysj.act_ru_variable.ID_</code>.
     */
    public final TableField<ActRuVariableRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_variable.REV_</code>.
     */
    public final TableField<ActRuVariableRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_ru_variable.TYPE_</code>.
     */
    public final TableField<ActRuVariableRecord, String> TYPE_ = createField(DSL.name("TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_variable.NAME_</code>.
     */
    public final TableField<ActRuVariableRecord, String> NAME_ = createField(DSL.name("NAME_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_variable.EXECUTION_ID_</code>.
     */
    public final TableField<ActRuVariableRecord, String> EXECUTION_ID_ = createField(DSL.name("EXECUTION_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_variable.PROC_INST_ID_</code>.
     */
    public final TableField<ActRuVariableRecord, String> PROC_INST_ID_ = createField(DSL.name("PROC_INST_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_variable.TASK_ID_</code>.
     */
    public final TableField<ActRuVariableRecord, String> TASK_ID_ = createField(DSL.name("TASK_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_variable.BYTEARRAY_ID_</code>.
     */
    public final TableField<ActRuVariableRecord, String> BYTEARRAY_ID_ = createField(DSL.name("BYTEARRAY_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_variable.DOUBLE_</code>.
     */
    public final TableField<ActRuVariableRecord, Double> DOUBLE_ = createField(DSL.name("DOUBLE_"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>bysj.act_ru_variable.LONG_</code>.
     */
    public final TableField<ActRuVariableRecord, Long> LONG_ = createField(DSL.name("LONG_"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bysj.act_ru_variable.TEXT_</code>.
     */
    public final TableField<ActRuVariableRecord, String> TEXT_ = createField(DSL.name("TEXT_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_ru_variable.TEXT2_</code>.
     */
    public final TableField<ActRuVariableRecord, String> TEXT2_ = createField(DSL.name("TEXT2_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * Create a <code>bysj.act_ru_variable</code> table reference
     */
    public ActRuVariable() {
        this(DSL.name("act_ru_variable"), null);
    }

    /**
     * Create an aliased <code>bysj.act_ru_variable</code> table reference
     */
    public ActRuVariable(String alias) {
        this(DSL.name(alias), ACT_RU_VARIABLE);
    }

    /**
     * Create an aliased <code>bysj.act_ru_variable</code> table reference
     */
    public ActRuVariable(Name alias) {
        this(alias, ACT_RU_VARIABLE);
    }

    private ActRuVariable(Name alias, Table<ActRuVariableRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActRuVariable(Name alias, Table<ActRuVariableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActRuVariable(Table<O> child, ForeignKey<O, ActRuVariableRecord> key) {
        super(child, key, ACT_RU_VARIABLE);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_RU_VARIABLE_ACT_FK_VAR_BYTEARRAY, Indexes.ACT_RU_VARIABLE_ACT_FK_VAR_EXE, Indexes.ACT_RU_VARIABLE_ACT_FK_VAR_PROCINST, Indexes.ACT_RU_VARIABLE_ACT_IDX_VARIABLE_TASK_ID, Indexes.ACT_RU_VARIABLE_PRIMARY);
    }

    @Override
    public UniqueKey<ActRuVariableRecord> getPrimaryKey() {
        return Keys.KEY_ACT_RU_VARIABLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActRuVariableRecord>> getKeys() {
        return Arrays.<UniqueKey<ActRuVariableRecord>>asList(Keys.KEY_ACT_RU_VARIABLE_PRIMARY);
    }

    @Override
    public List<ForeignKey<ActRuVariableRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActRuVariableRecord, ?>>asList(Keys.ACT_FK_VAR_EXE, Keys.ACT_FK_VAR_PROCINST, Keys.ACT_FK_VAR_BYTEARRAY);
    }

    public ActRuExecution actFkVarExe() {
        return new ActRuExecution(this, Keys.ACT_FK_VAR_EXE);
    }

    public ActRuExecution actFkVarProcinst() {
        return new ActRuExecution(this, Keys.ACT_FK_VAR_PROCINST);
    }

    public ActGeBytearray actGeBytearray() {
        return new ActGeBytearray(this, Keys.ACT_FK_VAR_BYTEARRAY);
    }

    @Override
    public ActRuVariable as(String alias) {
        return new ActRuVariable(DSL.name(alias), this);
    }

    @Override
    public ActRuVariable as(Name alias) {
        return new ActRuVariable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuVariable rename(String name) {
        return new ActRuVariable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuVariable rename(Name name) {
        return new ActRuVariable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, Integer, String, String, String, String, String, String, Double, Long, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
