/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActRuDeadletterJobRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuDeadletterJob extends TableImpl<ActRuDeadletterJobRecord> {

    private static final long serialVersionUID = 596946938;

    /**
     * The reference instance of <code>bysj.act_ru_deadletter_job</code>
     */
    public static final ActRuDeadletterJob ACT_RU_DEADLETTER_JOB = new ActRuDeadletterJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActRuDeadletterJobRecord> getRecordType() {
        return ActRuDeadletterJobRecord.class;
    }

    /**
     * The column <code>bysj.act_ru_deadletter_job.ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.REV_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.TYPE_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> TYPE_ = createField(DSL.name("TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.EXCLUSIVE_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, Byte> EXCLUSIVE_ = createField(DSL.name("EXCLUSIVE_"), org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.EXECUTION_ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> EXECUTION_ID_ = createField(DSL.name("EXECUTION_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.PROCESS_INSTANCE_ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> PROCESS_INSTANCE_ID_ = createField(DSL.name("PROCESS_INSTANCE_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.PROC_DEF_ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> PROC_DEF_ID_ = createField(DSL.name("PROC_DEF_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.EXCEPTION_STACK_ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> EXCEPTION_STACK_ID_ = createField(DSL.name("EXCEPTION_STACK_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.EXCEPTION_MSG_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> EXCEPTION_MSG_ = createField(DSL.name("EXCEPTION_MSG_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.DUEDATE_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, Timestamp> DUEDATE_ = createField(DSL.name("DUEDATE_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.REPEAT_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> REPEAT_ = createField(DSL.name("REPEAT_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.HANDLER_TYPE_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> HANDLER_TYPE_ = createField(DSL.name("HANDLER_TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.HANDLER_CFG_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> HANDLER_CFG_ = createField(DSL.name("HANDLER_CFG_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_ru_deadletter_job.TENANT_ID_</code>.
     */
    public final TableField<ActRuDeadletterJobRecord, String> TENANT_ID_ = createField(DSL.name("TENANT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>bysj.act_ru_deadletter_job</code> table reference
     */
    public ActRuDeadletterJob() {
        this(DSL.name("act_ru_deadletter_job"), null);
    }

    /**
     * Create an aliased <code>bysj.act_ru_deadletter_job</code> table reference
     */
    public ActRuDeadletterJob(String alias) {
        this(DSL.name(alias), ACT_RU_DEADLETTER_JOB);
    }

    /**
     * Create an aliased <code>bysj.act_ru_deadletter_job</code> table reference
     */
    public ActRuDeadletterJob(Name alias) {
        this(alias, ACT_RU_DEADLETTER_JOB);
    }

    private ActRuDeadletterJob(Name alias, Table<ActRuDeadletterJobRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActRuDeadletterJob(Name alias, Table<ActRuDeadletterJobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActRuDeadletterJob(Table<O> child, ForeignKey<O, ActRuDeadletterJobRecord> key) {
        super(child, key, ACT_RU_DEADLETTER_JOB);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_RU_DEADLETTER_JOB_ACT_FK_DEADLETTER_JOB_EXCEPTION, Indexes.ACT_RU_DEADLETTER_JOB_ACT_FK_DEADLETTER_JOB_EXECUTION, Indexes.ACT_RU_DEADLETTER_JOB_ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE, Indexes.ACT_RU_DEADLETTER_JOB_ACT_FK_DEADLETTER_JOB_PROC_DEF, Indexes.ACT_RU_DEADLETTER_JOB_PRIMARY);
    }

    @Override
    public UniqueKey<ActRuDeadletterJobRecord> getPrimaryKey() {
        return Keys.KEY_ACT_RU_DEADLETTER_JOB_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActRuDeadletterJobRecord>> getKeys() {
        return Arrays.<UniqueKey<ActRuDeadletterJobRecord>>asList(Keys.KEY_ACT_RU_DEADLETTER_JOB_PRIMARY);
    }

    @Override
    public List<ForeignKey<ActRuDeadletterJobRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActRuDeadletterJobRecord, ?>>asList(Keys.ACT_FK_DEADLETTER_JOB_EXECUTION, Keys.ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE, Keys.ACT_FK_DEADLETTER_JOB_PROC_DEF, Keys.ACT_FK_DEADLETTER_JOB_EXCEPTION);
    }

    public ActRuExecution actFkDeadletterJobExecution() {
        return new ActRuExecution(this, Keys.ACT_FK_DEADLETTER_JOB_EXECUTION);
    }

    public ActRuExecution actFkDeadletterJobProcessInstance() {
        return new ActRuExecution(this, Keys.ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE);
    }

    public ActReProcdef actReProcdef() {
        return new ActReProcdef(this, Keys.ACT_FK_DEADLETTER_JOB_PROC_DEF);
    }

    public ActGeBytearray actGeBytearray() {
        return new ActGeBytearray(this, Keys.ACT_FK_DEADLETTER_JOB_EXCEPTION);
    }

    @Override
    public ActRuDeadletterJob as(String alias) {
        return new ActRuDeadletterJob(DSL.name(alias), this);
    }

    @Override
    public ActRuDeadletterJob as(Name alias) {
        return new ActRuDeadletterJob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuDeadletterJob rename(String name) {
        return new ActRuDeadletterJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuDeadletterJob rename(Name name) {
        return new ActRuDeadletterJob(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, Integer, String, Byte, String, String, String, String, String, Timestamp, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
