/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ActRuTimerJobRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row17;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuTimerJob extends TableImpl<ActRuTimerJobRecord> {

    private static final long serialVersionUID = -1873215576;

    /**
     * The reference instance of <code>bysj.act_ru_timer_job</code>
     */
    public static final ActRuTimerJob ACT_RU_TIMER_JOB = new ActRuTimerJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActRuTimerJobRecord> getRecordType() {
        return ActRuTimerJobRecord.class;
    }

    /**
     * The column <code>bysj.act_ru_timer_job.ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> ID_ = createField(DSL.name("ID_"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.REV_</code>.
     */
    public final TableField<ActRuTimerJobRecord, Integer> REV_ = createField(DSL.name("REV_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.TYPE_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> TYPE_ = createField(DSL.name("TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.LOCK_EXP_TIME_</code>.
     */
    public final TableField<ActRuTimerJobRecord, Timestamp> LOCK_EXP_TIME_ = createField(DSL.name("LOCK_EXP_TIME_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.LOCK_OWNER_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> LOCK_OWNER_ = createField(DSL.name("LOCK_OWNER_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.EXCLUSIVE_</code>.
     */
    public final TableField<ActRuTimerJobRecord, Byte> EXCLUSIVE_ = createField(DSL.name("EXCLUSIVE_"), org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.EXECUTION_ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> EXECUTION_ID_ = createField(DSL.name("EXECUTION_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.PROCESS_INSTANCE_ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> PROCESS_INSTANCE_ID_ = createField(DSL.name("PROCESS_INSTANCE_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.PROC_DEF_ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> PROC_DEF_ID_ = createField(DSL.name("PROC_DEF_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.RETRIES_</code>.
     */
    public final TableField<ActRuTimerJobRecord, Integer> RETRIES_ = createField(DSL.name("RETRIES_"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.EXCEPTION_STACK_ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> EXCEPTION_STACK_ID_ = createField(DSL.name("EXCEPTION_STACK_ID_"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.EXCEPTION_MSG_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> EXCEPTION_MSG_ = createField(DSL.name("EXCEPTION_MSG_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.DUEDATE_</code>.
     */
    public final TableField<ActRuTimerJobRecord, Timestamp> DUEDATE_ = createField(DSL.name("DUEDATE_"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.REPEAT_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> REPEAT_ = createField(DSL.name("REPEAT_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.HANDLER_TYPE_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> HANDLER_TYPE_ = createField(DSL.name("HANDLER_TYPE_"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.HANDLER_CFG_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> HANDLER_CFG_ = createField(DSL.name("HANDLER_CFG_"), org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>bysj.act_ru_timer_job.TENANT_ID_</code>.
     */
    public final TableField<ActRuTimerJobRecord, String> TENANT_ID_ = createField(DSL.name("TENANT_ID_"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>bysj.act_ru_timer_job</code> table reference
     */
    public ActRuTimerJob() {
        this(DSL.name("act_ru_timer_job"), null);
    }

    /**
     * Create an aliased <code>bysj.act_ru_timer_job</code> table reference
     */
    public ActRuTimerJob(String alias) {
        this(DSL.name(alias), ACT_RU_TIMER_JOB);
    }

    /**
     * Create an aliased <code>bysj.act_ru_timer_job</code> table reference
     */
    public ActRuTimerJob(Name alias) {
        this(alias, ACT_RU_TIMER_JOB);
    }

    private ActRuTimerJob(Name alias, Table<ActRuTimerJobRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActRuTimerJob(Name alias, Table<ActRuTimerJobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActRuTimerJob(Table<O> child, ForeignKey<O, ActRuTimerJobRecord> key) {
        super(child, key, ACT_RU_TIMER_JOB);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACT_RU_TIMER_JOB_ACT_FK_TIMER_JOB_EXCEPTION, Indexes.ACT_RU_TIMER_JOB_ACT_FK_TIMER_JOB_EXECUTION, Indexes.ACT_RU_TIMER_JOB_ACT_FK_TIMER_JOB_PROCESS_INSTANCE, Indexes.ACT_RU_TIMER_JOB_ACT_FK_TIMER_JOB_PROC_DEF, Indexes.ACT_RU_TIMER_JOB_PRIMARY);
    }

    @Override
    public UniqueKey<ActRuTimerJobRecord> getPrimaryKey() {
        return Keys.KEY_ACT_RU_TIMER_JOB_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActRuTimerJobRecord>> getKeys() {
        return Arrays.<UniqueKey<ActRuTimerJobRecord>>asList(Keys.KEY_ACT_RU_TIMER_JOB_PRIMARY);
    }

    @Override
    public List<ForeignKey<ActRuTimerJobRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActRuTimerJobRecord, ?>>asList(Keys.ACT_FK_TIMER_JOB_EXECUTION, Keys.ACT_FK_TIMER_JOB_PROCESS_INSTANCE, Keys.ACT_FK_TIMER_JOB_PROC_DEF, Keys.ACT_FK_TIMER_JOB_EXCEPTION);
    }

    public ActRuExecution actFkTimerJobExecution() {
        return new ActRuExecution(this, Keys.ACT_FK_TIMER_JOB_EXECUTION);
    }

    public ActRuExecution actFkTimerJobProcessInstance() {
        return new ActRuExecution(this, Keys.ACT_FK_TIMER_JOB_PROCESS_INSTANCE);
    }

    public ActReProcdef actReProcdef() {
        return new ActReProcdef(this, Keys.ACT_FK_TIMER_JOB_PROC_DEF);
    }

    public ActGeBytearray actGeBytearray() {
        return new ActGeBytearray(this, Keys.ACT_FK_TIMER_JOB_EXCEPTION);
    }

    @Override
    public ActRuTimerJob as(String alias) {
        return new ActRuTimerJob(DSL.name(alias), this);
    }

    @Override
    public ActRuTimerJob as(Name alias) {
        return new ActRuTimerJob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuTimerJob rename(String name) {
        return new ActRuTimerJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuTimerJob rename(Name name) {
        return new ActRuTimerJob(name, null);
    }

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row17<String, Integer, String, Timestamp, String, Byte, String, String, String, Integer, String, String, Timestamp, String, String, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }
}
