/*
 * This file is generated by jOOQ.
 */
package com.heman.bysj.jooq.tables;


import com.heman.bysj.jooq.Bysj;
import com.heman.bysj.jooq.Indexes;
import com.heman.bysj.jooq.Keys;
import com.heman.bysj.jooq.tables.records.ExamineRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examine extends TableImpl<ExamineRecord> {

    private static final long serialVersionUID = -1290587773;

    /**
     * The reference instance of <code>bysj.examine</code>
     */
    public static final Examine EXAMINE = new Examine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExamineRecord> getRecordType() {
        return ExamineRecord.class;
    }

    /**
     * The column <code>bysj.examine.checkId</code>. 审批ID
     */
    public final TableField<ExamineRecord, String> CHECKID = createField(DSL.name("checkId"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "审批ID");

    /**
     * The column <code>bysj.examine.processInstanceId</code>. activiti流程实例ID
     */
    public final TableField<ExamineRecord, String> PROCESSINSTANCEID = createField(DSL.name("processInstanceId"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "activiti流程实例ID");

    /**
     * The column <code>bysj.examine.taskId</code>. activiti任务ID
     */
    public final TableField<ExamineRecord, String> TASKID = createField(DSL.name("taskId"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "activiti任务ID");

    /**
     * The column <code>bysj.examine.userID</code>. 请假用户ID
     */
    public final TableField<ExamineRecord, Integer> USERID = createField(DSL.name("userID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "请假用户ID");

    /**
     * The column <code>bysj.examine.role</code>. 请假用户角色
     */
    public final TableField<ExamineRecord, String> ROLE = createField(DSL.name("role"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "请假用户角色");

    /**
     * The column <code>bysj.examine.checkResult</code>. 审批结果：0 不通过，1 通过
     */
    public final TableField<ExamineRecord, String> CHECKRESULT = createField(DSL.name("checkResult"), org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "审批结果：0 不通过，1 通过");

    /**
     * The column <code>bysj.examine.opinion</code>. 审批意见
     */
    public final TableField<ExamineRecord, String> OPINION = createField(DSL.name("opinion"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "审批意见");

    /**
     * The column <code>bysj.examine.checkTime</code>. 审批日期
     */
    public final TableField<ExamineRecord, Timestamp> CHECKTIME = createField(DSL.name("checkTime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "审批日期");

    /**
     * Create a <code>bysj.examine</code> table reference
     */
    public Examine() {
        this(DSL.name("examine"), null);
    }

    /**
     * Create an aliased <code>bysj.examine</code> table reference
     */
    public Examine(String alias) {
        this(DSL.name(alias), EXAMINE);
    }

    /**
     * Create an aliased <code>bysj.examine</code> table reference
     */
    public Examine(Name alias) {
        this(alias, EXAMINE);
    }

    private Examine(Name alias, Table<ExamineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Examine(Name alias, Table<ExamineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Examine(Table<O> child, ForeignKey<O, ExamineRecord> key) {
        super(child, key, EXAMINE);
    }

    @Override
    public Schema getSchema() {
        return Bysj.BYSJ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EXAMINE_PRIMARY);
    }

    @Override
    public UniqueKey<ExamineRecord> getPrimaryKey() {
        return Keys.KEY_EXAMINE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ExamineRecord>> getKeys() {
        return Arrays.<UniqueKey<ExamineRecord>>asList(Keys.KEY_EXAMINE_PRIMARY);
    }

    @Override
    public Examine as(String alias) {
        return new Examine(DSL.name(alias), this);
    }

    @Override
    public Examine as(Name alias) {
        return new Examine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Examine rename(String name) {
        return new Examine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Examine rename(Name name) {
        return new Examine(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
